"""Generate the Rust protocol tables for hyperion-minecraft-proto.

Only facts that came out of Mojang's own data are emitted here: the protocol
number, the packet id tables, and the registries. Wire codecs are deliberately
not generated -- see docs/minecraft-26.2-migration.md for why that is a design
decision rather than an omission.

Mojang's names are used verbatim, because as of 26.1 they are the real names
rather than a community mapping, and matching them makes every generated symbol
greppable against the decompiled server.
"""

from __future__ import annotations

import argparse
import json
import keyword
from pathlib import Path

HEADER = """\
// @generated by nix/generate-rust.py from Minecraft {version} (protocol {protocol}).
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-proto
"""

STATES = ["handshake", "status", "login", "configuration", "play"]
DIRECTIONS = ["serverbound", "clientbound"]


def pascal(name: str) -> str:
    """minecraft:add_entity -> AddEntity."""
    bare = name.split(":", 1)[-1].replace("/", "_")
    return "".join(part.capitalize() for part in bare.split("_") if part)


def snake(name: str) -> str:
    bare = name.split(":", 1)[-1].replace("/", "_")
    return f"r#{bare}" if keyword.iskeyword(bare) else bare


def screaming(name: str) -> str:
    return snake(name).upper()


def emit_version(doc: dict) -> str:
    v = doc["version"]
    body = [
        "",
        "/// Wire protocol number sent in the handshake packet.",
        "pub const PROTOCOL_VERSION: i32 = {};".format(v["protocolVersion"]),
        "",
        "/// Human-readable game version this protocol belongs to.",
        'pub const MINECRAFT_VERSION: &str = "{}";'.format(v["id"]),
        "",
        "/// Data (world/chunk storage) version, distinct from the wire protocol number.",
        "pub const WORLD_VERSION: i32 = {};".format(v["worldVersion"]),
        "",
    ]
    return HEADER.format(version=v["id"], protocol=v["protocolVersion"]) + "\n".join(body)


def emit_packet_ids(doc: dict) -> str:
    v = doc["version"]
    out = [HEADER.format(version=v["id"], protocol=v["protocolVersion"])]
    out.append("""
/// Connection state a packet id is scoped to.
///
/// Ids restart at zero in every state and direction, so an id is only
/// meaningful alongside both.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum State {
    Handshake,
    Status,
    Login,
    Configuration,
    Play,
}

/// Which side of the connection sends a packet.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Direction {
    /// Client to server.
    Serverbound,
    /// Server to client.
    Clientbound,
}
""")

    by_key: dict[tuple[str, str], list[dict]] = {}
    for p in doc["packets"]:
        by_key.setdefault((p["state"], p["direction"]), []).append(p)

    for state in STATES:
        mods = []
        for direction in DIRECTIONS:
            packets = sorted(by_key.get((state, direction), []), key=lambda p: p["protocolId"])
            if not packets:
                continue
            mods.append(emit_enum(state, direction, packets))
        if mods:
            out.append("pub mod {} {{\n".format(state))
            out.append("\n".join(mods))
            out.append("}\n")
    return "".join(out)


def emit_enum(state: str, direction: str, packets: list[dict]) -> str:
    lines = ["    /// `{}` packets sent {}.\n".format(state, direction)]
    lines.append("    pub mod {} {{\n".format(direction))
    lines.append("""        /// Numeric packet id for the `{state}` / `{direction}` channel.
        ///
        /// Discriminants are the on-wire ids taken from Mojang's data
        /// generator and cross-checked against the registration order in the
        /// server's own protocol builder.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        #[repr(i32)]
        #[non_exhaustive]
        pub enum PacketId {{
""".format(state=state, direction=direction))
    for p in packets:
        doc_bit = " (`{}`)".format(p["javaClass"]) if p["javaClass"] else ""
        lines.append("            /// `{}`{}\n".format(p["resource"], doc_bit))
        lines.append("            {} = {},\n".format(pascal(p["resource"]), p["protocolId"]))
    lines.append("        }\n\n")

    lines.append("        impl PacketId {\n")
    lines.append("            /// Every packet in this channel, in id order.\n")
    lines.append("            pub const ALL: &'static [Self] = &[\n")
    for p in packets:
        lines.append("                Self::{},\n".format(pascal(p["resource"])))
    lines.append("            ];\n\n")

    lines.append("""            /// Numeric id as written on the wire.
            #[must_use]
            pub const fn to_raw(self) -> i32 {
                self as i32
            }

            /// Resolve an on-wire id, returning `None` for ids this protocol
            /// version does not define.
            #[must_use]
            pub const fn from_raw(id: i32) -> Option<Self> {
                match id {
""")
    for p in packets:
        lines.append("                    {} => Some(Self::{}),\n".format(p["protocolId"], pascal(p["resource"])))
    lines.append("""                    _ => None,
                }
            }

            /// Mojang resource name, e.g. `minecraft:add_entity`.
            #[must_use]
            pub const fn resource(self) -> &'static str {
                match self {
""")
    for p in packets:
        lines.append('                    Self::{} => "{}",\n'.format(pascal(p["resource"]), p["resource"]))
    lines.append("""                }
            }

            /// Name of the class implementing this packet in the server jar,
            /// useful when checking a layout against the decompiled source.
            #[must_use]
            pub const fn java_class(self) -> Option<&'static str> {
                match self {
""")
    for p in packets:
        cls = 'Some("{}")'.format(p["javaClass"]) if p["javaClass"] else "None"
        lines.append("                    Self::{} => {},\n".format(pascal(p["resource"]), cls))
    lines.append("""                }
            }
        }
""")
    lines.append("    }\n")
    return "".join(lines)


def emit_registries(doc: dict) -> str:
    v = doc["version"]
    out = [HEADER.format(version=v["id"], protocol=v["protocolVersion"])]
    out.append("""
/// A vanilla registry: entry names indexed by their network id.
///
/// Network ids are positional, so the index into [`Registry::entries`] is the
/// id that appears on the wire.
#[derive(Debug, Clone, Copy)]
pub struct Registry {
    /// Registry name, e.g. `minecraft:block`.
    pub name: &'static str,
    /// Entry names in network-id order.
    pub entries: &'static [&'static str],
}

impl Registry {
    /// Look up an entry by its network id.
    #[must_use]
    pub fn get(&self, id: usize) -> Option<&'static str> {
        self.entries.get(id).copied()
    }

    /// Look up the network id of an entry name.
    #[must_use]
    pub fn id_of(&self, name: &str) -> Option<usize> {
        self.entries.iter().position(|entry| *entry == name)
    }
}
""")

    consts = []
    for name, body in doc["registries"].items():
        const = screaming(name)
        consts.append(const)
        out.append("\n/// `{}` ({} entries).\n".format(name, len(body["entries"])))
        out.append("pub static {}: Registry = Registry {{\n".format(const))
        out.append('    name: "{}",\n'.format(name))
        out.append("    entries: &[\n")
        for entry in body["entries"]:
            out.append('        "{}",\n'.format(entry))
        out.append("    ],\n};\n")

    out.append("\n/// Every registry the server reports, in name order.\n")
    out.append("pub static ALL: &[&Registry] = &[\n")
    for const in consts:
        out.append("    &{},\n".format(const))
    out.append("];\n")
    return "".join(out)


def emit_mod(doc: dict) -> str:
    v = doc["version"]
    return HEADER.format(version=v["id"], protocol=v["protocolVersion"]) + """
//! Tables generated from Mojang's own data for this protocol version.
//!
//! Nothing in here is hand-written, and nothing in here encodes a wire layout:
//! layouts live in the hand-written codec modules alongside this one.

pub mod packet_id;
pub mod registry;
pub mod version;

pub use version::{MINECRAFT_VERSION, PROTOCOL_VERSION, WORLD_VERSION};
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--protocol", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    doc = json.loads(args.protocol.read_text())
    args.out.mkdir(parents=True, exist_ok=True)

    written = {
        "mod.rs": emit_mod(doc),
        "version.rs": emit_version(doc),
        "packet_id.rs": emit_packet_ids(doc),
        "registry.rs": emit_registries(doc),
    }
    for name, text in written.items():
        (args.out / name).write_text(text)
        print("{}: {} bytes".format(name, len(text)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
