"""Generate the Rust protocol tables for hyperion-minecraft-proto.

Everything here is a fact read out of Mojang's own data: the protocol number,
the packet id tables, the registries, the data component types an item can
carry, and the wire layout of each packet and component whose codec the
extractor could follow all the way to the bytes.

Layouts that could not be followed are absent rather than approximated. The
accessors return Option and the generator refuses to run on a wire kind it has
no variant for, so a layout that comes out of the generated tables is one whose
whole byte sequence is known.

Mojang's names are used verbatim, because as of 26.1 they are the real names
rather than a community mapping, and matching them makes every generated symbol
greppable against the decompiled server.
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
from pathlib import Path

HEADER = """\
// @generated by nix/generate-rust.py from Minecraft {version} (protocol {protocol}).
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-proto
"""

STATES = ["handshake", "status", "login", "configuration", "play"]
DIRECTIONS = ["serverbound", "clientbound"]


def pascal(name: str) -> str:
    """minecraft:add_entity -> AddEntity."""
    bare = name.split(":", 1)[-1].replace("/", "_")
    return "".join(part.capitalize() for part in bare.split("_") if part)


def snake(name: str) -> str:
    bare = name.split(":", 1)[-1].replace("/", "_")
    return f"r#{bare}" if keyword.iskeyword(bare) else bare


def screaming(name: str) -> str:
    return snake(name).upper()


def grouped_arms(arms: list[tuple[str, str]], indent: str) -> str:
    """Render match arms, merging the ones that share a body.

    Two components that reuse the same codec produce the same arm, and
    clippy::match_same_arms rejects that, so equal bodies are merged into one
    pattern in first-appearance order.
    """
    order: list[str] = []
    patterns: dict[str, list[str]] = {}
    for pattern, body in arms:
        if body not in patterns:
            patterns[body] = []
            order.append(body)
        patterns[body].append(pattern)
    return "".join(
        "{}{} => {},\n".format(indent, " | ".join(patterns[body]), body) for body in order
    )


def emit_version(doc: dict) -> str:
    v = doc["version"]
    body = [
        "",
        "/// Wire protocol number sent in the handshake packet.",
        "pub const PROTOCOL_VERSION: i32 = {};".format(v["protocolVersion"]),
        "",
        "/// Human-readable game version this protocol belongs to.",
        'pub const MINECRAFT_VERSION: &str = "{}";'.format(v["id"]),
        "",
        "/// Data (world/chunk storage) version, distinct from the wire protocol number.",
        "pub const WORLD_VERSION: i32 = {};".format(v["worldVersion"]),
        "",
    ]
    return HEADER.format(version=v["id"], protocol=v["protocolVersion"]) + "\n".join(body)


def emit_packet_ids(doc: dict, emitter: WireEmitter) -> str:
    v = doc["version"]
    out = [HEADER.format(version=v["id"], protocol=v["protocolVersion"])]
    out.append("""
/// Connection state a packet id is scoped to.
///
/// Ids restart at zero in every state and direction, so an id is only
/// meaningful alongside both.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum State {
    Handshake,
    Status,
    Login,
    Configuration,
    Play,
}

/// Which side of the connection sends a packet.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Direction {
    /// Client to server.
    Serverbound,
    /// Server to client.
    Clientbound,
}
""")

    by_key: dict[tuple[str, str], list[dict]] = {}
    for p in doc["packets"]:
        by_key.setdefault((p["state"], p["direction"]), []).append(p)

    for state in STATES:
        mods = []
        for direction in DIRECTIONS:
            packets = sorted(by_key.get((state, direction), []), key=lambda p: p["protocolId"])
            if not packets:
                continue
            mods.append(emit_enum(state, direction, packets, emitter))
        if mods:
            out.append("pub mod {} {{\n".format(state))
            out.append("\n".join(mods))
            out.append("}\n")
    return "".join(out)


def emit_enum(state: str, direction: str, packets: list[dict], emitter: WireEmitter) -> str:
    lines = ["    /// `{}` packets sent {}.\n".format(state, direction)]
    lines.append("    pub mod {} {{\n".format(direction))
    lines.append("")
    lines.append("""        /// Numeric packet id for the `{state}` / `{direction}` channel.
        ///
        /// Discriminants are the on-wire ids taken from Mojang's data
        /// generator and cross-checked against the registration order in the
        /// server's own protocol builder.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        #[repr(i32)]
        #[non_exhaustive]
        pub enum PacketId {{
""".format(state=state, direction=direction))
    for p in packets:
        doc_bit = " (`{}`)".format(p["javaClass"]) if p["javaClass"] else ""
        lines.append("            /// `{}`{}\n".format(p["resource"], doc_bit))
        lines.append("            {} = {},\n".format(pascal(p["resource"]), p["protocolId"]))
    lines.append("        }\n\n")

    lines.append("        impl PacketId {\n")
    lines.append("            /// Every packet in this channel, in id order.\n")
    lines.append("            pub const ALL: &'static [Self] = &[\n")
    for p in packets:
        lines.append("                Self::{},\n".format(pascal(p["resource"])))
    lines.append("            ];\n\n")

    lines.append("""            /// Numeric id as written on the wire.
            #[must_use]
            pub const fn to_raw(self) -> i32 {
                self as i32
            }

            /// Resolve an on-wire id, returning `None` for ids this protocol
            /// version does not define.
            #[must_use]
            pub const fn from_raw(id: i32) -> Option<Self> {
                match id {
""")
    for p in packets:
        lines.append("                    {} => Some(Self::{}),\n".format(p["protocolId"], pascal(p["resource"])))
    lines.append("""                    _ => None,
                }
            }

            /// Mojang resource name, e.g. `minecraft:add_entity`.
            #[must_use]
            pub const fn resource(self) -> &'static str {
                match self {
""")
    for p in packets:
        lines.append('                    Self::{} => "{}",\n'.format(pascal(p["resource"]), p["resource"]))
    lines.append("""                }
            }

            /// Name of the class implementing this packet in the server jar,
            /// useful when checking a layout against the decompiled source.
            #[must_use]
            pub const fn java_class(self) -> Option<&'static str> {
                match self {
""")
    for p in packets:
        cls = 'Some("{}")'.format(p["javaClass"]) if p["javaClass"] else "None"
        lines.append("                    Self::{} => {},\n".format(pascal(p["resource"]), cls))
    lines.append("""                }
            }

            /// Wire layout of the packet body, or `None` where the server's
            /// own codec branches on a runtime value and no fixed layout
            /// exists.
            #[must_use]
            pub const fn layout(self) -> Option<&'static crate::generated::wire::Wire> {
                match self {
""")
    layout_arms: list[tuple[str, str]] = []
    for p in packets:
        if not p["complete"]:
            continue
        hint = "{}_{}_{}".format(state, direction, p["resource"])
        layout_arms.append(
            ("Self::" + pascal(p["resource"]), "Some({})".format(emitter.reference(hint, p["wire"]))))
    lines.append(grouped_arms(layout_arms, " " * 20))
    # A catch-all rather than a None arm per packet, since those arms would be
    # identical and clippy::match_same_arms rejects that; omitted entirely when
    # every packet in the channel has a layout, or it is unreachable.
    if len(layout_arms) != len(packets):
        lines.append("                    _ => None,\n")
    lines.append("""                }
            }
        }
""")
    lines.append("    }\n")
    return "".join(lines)


# ---------------------------------------------------------------------------
# Registries, as closed Rust enums
#
# A registry entry reaches Rust as a variant and not as a string, so a caller
# cannot name a value the game does not have. The id it would have sent is the
# variant's own discriminant -- `#[repr]` is chosen so the discriminant *is*
# the network id -- which makes `id()` an `as` cast the optimiser folds away
# rather than a lookup through a table or a match.
#
# Nothing here is curated. Every registry the extractor reports gets an enum,
# because a hand-picked subset is a gap that surfaces the day somebody needs
# the registry nobody picked.
# ---------------------------------------------------------------------------

# Rust identifiers are case-sensitive, so a collision is an exact string
# collision and this is the whole test. It runs inside the generator rather
# than in a test, because an identifier that collides does not compile and the
# useful failure is the one naming which two entries did it.
VARIANT = re.compile(r"^[A-Z][A-Za-z0-9]*$")


def variant(entry: str) -> str:
    """`minecraft:ambient.cave` -> AmbientCave, `brigadier:bool` -> BrigadierBool.

    The namespace is dropped for `minecraft:` and folded in otherwise, so the
    six `brigadier:` command argument types cannot collide with a vanilla path
    spelled the same way.
    """
    namespace, _, path = entry.partition(":")
    source = path if namespace == "minecraft" else entry.replace(":", "_")
    return "".join(word[:1].upper() + word[1:] for word in re.split(r"[._/-]", source) if word)


def repr_width(count: int) -> str:
    """The narrowest unsigned repr that holds every id in the registry.

    The discriminant is the network id, so the repr is also how much a value
    costs to hold and to move. Nothing wants four bytes for a registry of five.
    """
    if count <= 1 << 8:
        return "u8"
    if count <= 1 << 16:
        return "u16"
    return "u32"


WIDTH_BYTES = {"u8": 1, "u16": 2, "u32": 4}

# The one registry with no enum here, and why.
#
# Not curation -- every other registry gets one whether or not anything uses
# it, because a hand-picked subset is a gap waiting to be found. This one is
# excluded because `protocol.json` is the wrong input for it. The extractor
# gives up on `ParticleTypes#STREAM_CODEC` ("dispatched codec: the layout
# depends on a runtime type"), so it reports the 125 names and nothing about
# their bodies -- and 13 of the 125 carry one: `block` a block state, `dust` a
# colour and a scale, `vibration` a destination and a flight time, and so on.
# An enum generated from this file would be id-only and structurally unable to
# say that, while being the more discoverable of the two names.
#
# A separate generator reads the decompiled codecs instead, which is where the
# payload shapes are. It follows the conventions below -- discriminant is the
# network id, `const fn id`, `name()` off a static table, `from_id`/`from_name`
# at the decode boundary only, closed, no `Unknown` -- and pins its ids against
# `PARTICLE_TYPE` here, which is what stops the two from drifting.
#
# The name table below therefore stays even though the enum does not, because
# it is what that generator pins against.
#
# Do not add this registry back without first deleting whatever generator owns
# the particle enum. Two enums over one registry, with the poorer one being the
# more discoverable name, is worse than either alone.
NO_ENUM: dict[str, str] = {
    "minecraft:particle_type": (
        "13 of its 125 entries carry payloads that `protocol.json` cannot "
        "describe, so the enum is generated from the decompiled codecs instead "
        "and lives outside this file"
    ),
}


def emit_registry_enum(doc: dict, name: str, entries: list[str]) -> str:
    """One registry, as an enum plus the two tables its accessors index."""
    v = doc["version"]
    ty = pascal(name)
    width = repr_width(len(entries))
    idents = [variant(entry) for entry in entries]

    seen: dict[str, str] = {}
    for entry, ident in zip(entries, idents):
        if ident in seen:
            raise SystemExit(
                "{}: `{}` and `{}` both become the variant `{}`; teach variant() a "
                "disambiguation rather than dropping one".format(name, seen[ident], entry, ident)
            )
        if not VARIANT.match(ident):
            raise SystemExit(
                "{}: `{}` becomes `{}`, which is not a Rust identifier".format(name, entry, ident)
            )
        seen[ident] = entry

    order = sorted(range(len(entries)), key=lambda index: entries[index])

    out = [HEADER.format(version=v["id"], protocol=v["protocolVersion"])]
    out.append('''
//! `{name}`, as a closed Rust enum.

use crate::types::RegistryId;

/// An entry of `{name}` ({count} of them).
///
/// Closed on purpose. Every value this version defines is a variant, so a
/// caller cannot name one that does not exist and a `match` never needs an arm
/// for a case that cannot occur. The one place a value might not be in the set
/// is an id arriving off the wire, and [`{ty}::from_id`] is the only door for
/// it.
///
/// The discriminant is the network id, so [`{ty}::id`] is an `as` cast: a
/// known variant's id folds to a constant at compile time.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[repr({width})]
pub enum {ty} {{
'''.format(name=name, ty=ty, count=len(entries), width=width))
    for index, (entry, ident) in enumerate(zip(entries, idents)):
        out.append("    /// `{}` (id {}).\n".format(entry, index))
        out.append("    {} = {},\n".format(ident, index))
    out.append("}\n")

    out.append('''
/// Entry names in network-id order, so the index is the id.
///
/// A table and not a `match`, so [`{ty}::name`] is one load from a static.
/// `crate::generated::registry::{const}` points at this same array, which is
/// what stops the two from disagreeing.
pub static NAMES_IN_ID_ORDER: [&str; {count}] = [
'''.format(ty=ty, const=screaming(name), count=len(entries)))
    for entry in entries:
        out.append('    "{}",\n'.format(entry))
    out.append("];\n")

    out.append('''
/// Discriminants ordered by name, so [`{ty}::from_name`] is a binary search
/// and not a scan.
///
/// Sorted here, at generation time, rather than assumed of the registry:
/// {unsorted}. A wrong order would fail as a lookup miss and read as "that
/// entry does not exist", so `tests/registry_enum.rs` puts every one of the
/// {count} names back through `from_name` rather than spot-checking.
static BY_NAME: [{width}; {count}] = [
'''.format(ty=ty,
           width=width,
           count=len(entries),
           unsorted=("this registry's own order is not name order"
                     if [entries[i] for i in order] != entries
                     else "this registry happens to be in name order already, "
                          "which is not something to rely on")))
    for index in order:
        out.append("    {},\n".format(index))
    out.append("];\n")

    out.append('''
impl {ty} {{
    /// The registry these values belong to.
    pub const REGISTRY: &'static str = "{name}";

    /// How many entries this version has, so every valid id is below it.
    pub const COUNT: usize = {count};

    /// Every entry, in network-id order, so the index is the id.
    pub const ALL: &'static [Self] = &[
'''.format(ty=ty, name=name, count=len(entries)))
    for ident in idents:
        out.append("        Self::{},\n".format(ident))
    out.append('''    ];

    /// The network id.
    ///
    /// `#[repr({width})]` on the enum is what makes this an `as` cast rather
    /// than a lookup: for a variant known at compile time the whole call folds
    /// to the number.
    #[must_use]
    pub const fn id(self) -> RegistryId {{
        RegistryId(self as i32)
    }}

    /// The namespaced name, e.g. `{first}`.
    ///
    /// Not `const`: it reads a static table. The direction that is const is
    /// [`Self::id`], which is the one that reaches the wire.
    #[must_use]
    pub fn name(self) -> &'static str {{
        NAMES_IN_ID_ORDER[self as usize]
    }}

    /// Resolve an id that arrived off the wire.
    ///
    /// The decode boundary, and the only place a `{ty}` can fail to exist.
    /// Every other path is holding a value that is already in the set.
    #[must_use]
    pub fn from_id(id: RegistryId) -> Option<Self> {{
        usize::try_from(id.0)
            .ok()
            .and_then(|index| Self::ALL.get(index).copied())
    }}

    /// Resolve a name only known at run time -- one read out of a world file,
    /// or typed into a command.
    ///
    /// A name known at compile time should be the variant instead, so that a
    /// version bump dropping it fails to build at the line that wanted it
    /// rather than returning `None` on whichever tick it was next needed.
    #[must_use]
    pub fn from_name(name: &str) -> Option<Self> {{
        let found = BY_NAME
            .binary_search_by(|&index| NAMES_IN_ID_ORDER[index as usize].cmp(name))
            .ok()?;
        Self::ALL.get(BY_NAME[found] as usize).copied()
    }}
}}

impl core::fmt::Display for {ty} {{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {{
        f.write_str(self.name())
    }}
}}

// The zero-cost claim, checked by the compiler rather than by a test.
//
// A `const` context cannot call anything the compiler is unable to evaluate at
// compile time, so if `id()` were ever a table lookup or a `match` over a
// runtime value instead of a cast off the discriminant, this line would stop
// building. It is the proof, not a restatement of it.
const _: () = assert!({ty}::ALL[{last}].id().0 == {last});

// And the size, for the same reason: `#[repr({width})]` is what makes the
// discriminant the id, and a value of this enum is that many bytes and no
// more. The old hand-written `EntityType` was a name pointer plus an `i32`,
// which is 16.
const _: () = assert!(core::mem::size_of::<{ty}>() == {bytes});
'''.format(ty=ty, width=width, first=entries[0], last=len(entries) - 1,
           bytes=WIDTH_BYTES[width]))
    return "".join(out)


def emit_names_only(doc: dict, name: str, entries: list[str]) -> str:
    """A registry with no enum: the name table alone, and why it has no enum."""
    v = doc["version"]
    out = [HEADER.format(version=v["id"], protocol=v["protocolVersion"])]
    out.append('''
//! `{name}` -- names only. This registry deliberately has no enum here.
//!
//! Reason: {reason}.
//!
//! Every other registry in this module is an enum whether or not anything uses
//! it, because a hand-picked subset is a gap waiting to be found. This one is
//! different in kind rather than in importance. The extractor cannot follow
//! `ParticleTypes#STREAM_CODEC` past its runtime dispatch, so `protocol.json`
//! carries these {count} names and nothing about their bodies -- and 13 of
//! them have one. An enum generated from this file could name a particle but
//! never carry its block state, its colour or its flight time, while being the
//! more discoverable of the two spellings.
//!
//! The table below stays, because it is what the generator that does own the
//! enum pins its ids against.

/// Entry names in network-id order, so the index is the id.
pub static NAMES_IN_ID_ORDER: [&str; {count}] = [
'''.format(name=name, reason=NO_ENUM[name], count=len(entries)))
    for entry in entries:
        out.append('    "{}",\n'.format(entry))
    out.append("];\n")
    return "".join(out)


def emit_registries(doc: dict) -> dict[str, str]:
    """`registry/mod.rs`, plus one file per registry."""
    v = doc["version"]
    registries = doc["registries"]

    files = {
        "registry/{}.rs".format(snake(name)): (
            emit_names_only(doc, name, body["entries"])
            if name in NO_ENUM
            else emit_registry_enum(doc, name, body["entries"])
        )
        for name, body in registries.items()
    }

    out = [HEADER.format(version=v["id"], protocol=v["protocolVersion"])]
    out.append("""
//! Every vanilla registry, as a closed Rust enum.
//!
//! A registry is positional: the number on the wire is an entry's index into
//! it, and that index moves whenever Mojang inserts an entry. The name is the
//! part that survives a version bump, so the id belongs to the generator and
//! the caller names the entry.
//!
//! Naming it as a *variant* rather than as a string is the point. A rename
//! becomes a build failure at the line that wanted the value, instead of a
//! `None` on whichever tick that value was next needed. Every enum here is
//! closed -- there is no `Unknown(u32)` -- because a value inside the server
//! has already been proven to be in the set. The one place that is not true is
//! an id arriving off the wire, and `from_id` is the only door for it.
//!
//! Nothing is curated: every registry the extractor reports has an enum, so
//! there is no subset to fall outside of. The single exception is
//! `minecraft:particle_type`, whose entries carry payloads this file's input
//! cannot describe; its enum is generated from the decompiled codecs instead,
//! and the reason is written at the top of the `particle_type` module here.
//!
//! # What is free and what is not
//!
//! `id()` is an `as` cast off the discriminant and folds to a constant.
//! `name()` is one load from a static table indexed by the discriminant.
//! `from_name()` is a binary search, and is for names that are genuinely only
//! known at run time.
//!
//! The first of those is not asserted in prose. Every registry file below ends
//! in a `const` assertion calling `id()`, and a `const` context cannot call
//! anything the compiler is unable to fold, so the build fails if `id()` ever
//! stops being free:
//!
//! ```
//! use hyperion_minecraft_proto::generated::registry::SoundEvent;
//! const ID: i32 = SoundEvent::EntityArrowHit.id().0;
//! const _: () = assert!(ID == 85);
//! ```
//!
//! # The set is closed
//!
//! There is no way to name a sound this version does not have. Not a `None` at
//! run time -- a compiler error, at the line that wanted it:
//!
//! ```compile_fail
//! use hyperion_minecraft_proto::generated::registry::SoundEvent;
//! // Invented, so this does not compile.
//! let _ = SoundEvent::EntityArrowHitDeluxe;
//! ```

use crate::types::RegistryId;

""")
    for name in registries:
        out.append("pub mod {};\n".format(snake(name)))
    out.append("\n")
    for name in registries:
        if name in NO_ENUM:
            continue
        out.append("pub use {}::{};\n".format(snake(name), pascal(name)))

    out.append("""
/// A vanilla registry: entry names indexed by their network id.
///
/// The name table each of these points at is the same array the registry's own
/// enum indexes for `name()`, so the two cannot disagree about what the
/// registry holds.
#[derive(Debug, Clone, Copy)]
pub struct Registry {
    /// Registry name, e.g. `minecraft:block`.
    pub name: &'static str,
    /// Entry names in network-id order.
    pub entries: &'static [&'static str],
}

impl Registry {
    /// Look up an entry by its network id.
    #[must_use]
    pub fn get(&self, id: usize) -> Option<&'static str> {
        self.entries.get(id).copied()
    }

    /// Look up the network id of an entry name.
    ///
    /// Linear, and there is usually something better: the registry's own
    /// `from_name` is a binary search, and naming the variant is no search at
    /// all. This stays for callers walking registries generically.
    #[must_use]
    pub fn id_of(&self, name: &str) -> Option<usize> {
        self.entries.iter().position(|entry| *entry == name)
    }
}

/// One registry's enum behind function pointers, so a test can walk all of
/// them rather than name 95 types by hand.
///
/// Only tests and tools use this. Nothing on a hot path goes through a
/// function pointer to reach a registry id.
#[derive(Debug, Clone, Copy)]
pub struct EnumRegistry {
    /// Registry name, e.g. `minecraft:block`.
    pub name: &'static str,
    /// The Rust type, so a failure message names it.
    pub rust_type: &'static str,
    /// How many entries, which is also how many variants.
    pub count: usize,
    /// Bytes of the enum's discriminant, which is `size_of` the enum.
    pub width: usize,
    /// `from_id`, then `name`.
    pub name_of: fn(i32) -> Option<&'static str>,
    /// `from_name`, then `id`.
    pub id_of: fn(&str) -> Option<i32>,
}
""")

    consts = []
    for name, body in registries.items():
        const = screaming(name)
        consts.append(const)
        out.append("\n/// `{}` ({} entries).\n".format(name, len(body["entries"])))
        out.append("pub static {}: Registry = Registry {{\n".format(const))
        out.append('    name: "{}",\n'.format(name))
        out.append("    entries: &{}::NAMES_IN_ID_ORDER,\n".format(snake(name)))
        out.append("};\n")

    out.append("\n/// Every registry the server reports, in name order.\n")
    out.append("pub static ALL: &[&Registry] = &[\n")
    for const in consts:
        out.append("    &{},\n".format(const))
    out.append("];\n")

    out.append("""
/// Every registry's enum, so one test covers all 95 of them.
pub static ALL_ENUMS: &[EnumRegistry] = &[
""")
    for name, body in registries.items():
        if name in NO_ENUM:
            continue
        out.append("""    EnumRegistry {{
        name: "{name}",
        rust_type: "{ty}",
        count: {count},
        width: {width},
        name_of: |id| {ty}::from_id(RegistryId(id)).map({ty}::name),
        id_of: |name| {ty}::from_name(name).map(|value| value.id().0),
    }},
""".format(name=name,
           ty=pascal(name),
           count=len(body["entries"]),
           width=WIDTH_BYTES[repr_width(len(body["entries"]))]))
    out.append("];\n")

    files["registry/mod.rs"] = "".join(out)
    return files


def emit_mod(doc: dict) -> str:
    v = doc["version"]
    return HEADER.format(version=v["id"], protocol=v["protocolVersion"]) + """
//! Tables generated from Mojang's own data for this protocol version.
//!
//! Nothing in here is hand-written. [`wire`] carries the layouts the extractor
//! could read off the server's own stream codecs; where it could not, the
//! layout is absent rather than approximated, and the hand-written codec
//! modules alongside this one cover the difference.

pub mod data_component;
pub mod packet_id;
pub mod registry;
pub mod version;
pub mod wire;

pub use data_component::DataComponent;
pub use version::{MINECRAFT_VERSION, PROTOCOL_VERSION, WORLD_VERSION};
pub use wire::{Constant, Field, Wire};
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--protocol", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    doc = json.loads(args.protocol.read_text())
    args.out.mkdir(parents=True, exist_ok=True)

    # One emitter across both files: a codec shared by a packet and a data
    # component is hoisted into a single static rather than written twice.
    emitter = WireEmitter(doc["types"])
    written = {
        "mod.rs": emit_mod(doc),
        "version.rs": emit_version(doc),
        "packet_id.rs": emit_packet_ids(doc, emitter),
        "data_component.rs": emit_data_components(doc, emitter),
        # Last, so every static the other files reference has been collected.
        "wire.rs": emit_wire(doc, emitter),
    }
    # One file per registry rather than one file of 95, so a reader opening
    # `registry/sound_event.rs` gets 1968 lines and not 35000.
    written.update(emit_registries(doc))
    for name, text in sorted(written.items()):
        path = args.out / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print("{}: {} bytes".format(name, len(text)))
    return 0


# ---------------------------------------------------------------------------
# Wire layouts
#
# Only layouts the extractor resolved all the way down are emitted, and the
# accessors return Option, so there is no way to get a layout back that is
# quietly missing a field. A packet or component whose codec branches on a
# runtime value simply has no layout here.
# ---------------------------------------------------------------------------

# Extractor wire kind -> Rust variant. A kind with no entry is a build failure
# rather than a silent omission: emitting an Unknown variant for it would hand
# callers a layout that looks usable and is short.
WIRE_VARIANTS: dict[str, str] = {
    "unit": "crate::generated::wire::Wire::Unit",
    "bool": "crate::generated::wire::Wire::Bool",
    "i8": "crate::generated::wire::Wire::I8",
    "i16": "crate::generated::wire::Wire::I16",
    "i32": "crate::generated::wire::Wire::I32",
    "i64": "crate::generated::wire::Wire::I64",
    "u16": "crate::generated::wire::Wire::U16",
    "f32": "crate::generated::wire::Wire::F32",
    "f64": "crate::generated::wire::Wire::F64",
    "varint": "crate::generated::wire::Wire::VarInt",
    "varlong": "crate::generated::wire::Wire::VarLong",
    "uuid": "crate::generated::wire::Wire::Uuid",
    "block_pos": "crate::generated::wire::Wire::BlockPos",
    "chunk_pos": "crate::generated::wire::Wire::ChunkPos",
    "block_hit_result": "crate::generated::wire::Wire::BlockHitResult",
    "identifier": "crate::generated::wire::Wire::Identifier",
    "nbt": "crate::generated::wire::Wire::Nbt",
    "optional_nbt": "crate::generated::wire::Wire::OptionalNbt",
    "long_array": "crate::generated::wire::Wire::LongArray",
    "varint_array": "crate::generated::wire::Wire::VarIntArray",
}


def rust_ident(key: str) -> str:
    """`net.minecraft.world.phys.Vec3#STREAM_CODEC` -> a static's name.

    The whole Java path is kept so the name cannot collide and so a reader can
    grep the generated static straight back to the class it came from.
    """
    return re.sub(r"[^A-Za-z0-9]+", "_", key).strip("_").upper()


# Statics and variants are written out fully qualified. The generated files
# reference each other, and a `use` that turns out unused in one of them is a
# denied lint, so the path is spelled rather than imported conditionally.
WIRE_PATH = "crate::generated::wire"


def rust_int(value: int) -> str:
    """262144 -> 262_144, which is what clippy::pedantic insists on."""
    text = str(value)
    groups = []
    while len(text) > 3:
        groups.insert(0, text[-3:])
        text = text[:-3]
    groups.insert(0, text)
    return "_".join(groups)


def option_u32(value: object) -> str:
    return "None" if value is None else "Some({})".format(rust_int(int(value)))


class WireEmitter:
    """Renders resolved wire types, hoisting named codecs into statics."""

    def __init__(self, types: dict[str, dict]) -> None:
        self.types = types
        self.emitted: dict[str, str] = {}
        self.order: list[str] = []

    def reference(self, hint: str, wire: dict) -> str:
        """A `&'static Wire` for a top-level layout.

        Always a static, never an inline literal: a `const fn` cannot return a
        reference to a temporary, so a layout that is a bare struct rather than
        a named codec still needs somewhere to live.
        """
        if wire["kind"] == "named":
            return self.expr(wire)
        name = "LAYOUT_{}".format(rust_ident(hint))
        if name not in self.emitted.values():
            self.order.append("/// Layout of `{}`.\npub(crate) static {}: Wire = {};\n".format(
                hint, name, self.value(wire)))
            self.emitted["layout:" + hint] = name
        return "&{}::{}".format(WIRE_PATH, name)

    def expr(self, wire: dict) -> str:
        """A `&'static Wire` expression, emitting any statics it needs."""
        if wire["kind"] == "named":
            return "&{}::{}".format(WIRE_PATH, self.static_for(wire["ref"]))
        return "&{}".format(self.value(wire))

    def value(self, wire: dict) -> str:
        kind = wire["kind"]
        if kind in WIRE_VARIANTS:
            return WIRE_VARIANTS[kind]
        if kind == "string":
            return "crate::generated::wire::Wire::Str {{ max: {} }}".format(option_u32(wire.get("max")))
        if kind == "byte_array":
            return "crate::generated::wire::Wire::ByteArray {{ max: {} }}".format(option_u32(wire.get("max")))
        if kind == "registry_id":
            return 'crate::generated::wire::Wire::RegistryId {{ registry: "{}" }}'.format(wire["registry"])
        if kind == "holder_set":
            return 'crate::generated::wire::Wire::HolderSet {{ registry: "{}" }}'.format(wire["registry"])
        if kind == "holder":
            return 'crate::generated::wire::Wire::Holder {{ registry: "{}", direct: {} }}'.format(
                wire["registry"], self.expr(wire["of"]))
        if kind == "option":
            return "crate::generated::wire::Wire::Optional({})".format(self.expr(wire["of"]))
        if kind == "list":
            return "crate::generated::wire::Wire::List {{ element: {}, max: {} }}".format(
                self.expr(wire["of"]), option_u32(wire.get("max")))
        if kind == "length_prefixed":
            return "crate::generated::wire::Wire::LengthPrefixed {{ value: {}, max: {} }}".format(
                self.expr(wire["of"]), option_u32(wire.get("max")))
        if kind == "map":
            return "crate::generated::wire::Wire::Map {{ key: {}, value: {} }}".format(
                self.expr(wire["key"]), self.expr(wire["value"]))
        if kind == "either":
            return "crate::generated::wire::Wire::Either {{ left: {}, right: {} }}".format(
                self.expr(wire["left"]), self.expr(wire["right"]))
        if kind == "enum":
            constants = ", ".join(
                'crate::generated::wire::Constant {{ name: "{}", value: {} }}'.format(c["name"], c["value"])
                for c in wire["constants"])
            return 'crate::generated::wire::Wire::Enum {{ java_class: "{}", constants: &[{}] }}'.format(
                wire["type"], constants)
        if kind == "custom":
            return 'crate::generated::wire::Wire::Custom {{ codec: "{}" }}'.format(wire["codec"])
        if kind == "struct":
            members = ", ".join(
                'crate::generated::wire::Field {{ name: "{}", wire: {} }}'.format(f["name"], self.expr(f["wire"]))
                for f in wire["fields"])
            return "crate::generated::wire::Wire::Struct(&[{}])".format(members)
        raise SystemExit("generate-rust.py has no Rust variant for wire kind {!r}".format(kind))

    def static_for(self, ref: str) -> str:
        name = self.emitted.get(ref)
        if name is not None:
            return name
        # A codec that is just another codec under a new name shares its
        # static: `static A: Wire = B;` is not a thing Rust will accept, and
        # duplicating the body would hide the sharing.
        alias = ref
        while self.types[alias]["kind"] == "named" and self.types[alias]["ref"] != alias:
            alias = self.types[alias]["ref"]
        if alias != ref:
            name = self.static_for(alias)
            self.emitted[ref] = name
            return name
        name = rust_ident(ref)
        # Recorded before rendering so a self-referential codec terminates.
        self.emitted[ref] = name
        body = self.value(self.types[ref])
        # pub(crate): the accessors handing out references to these live in
        # sibling modules, but the name itself is not part of the API.
        self.order.append(
            "/// `{}`\npub(crate) static {}: Wire = {};\n".format(ref, name, body))
        return name


WIRE_PREAMBLE = """
//! Wire layouts read off the server's own stream codecs.
//!
//! A layout is only present when the extractor followed it all the way to the
//! bytes, and every accessor returns `Option`. Anything whose encoder branches
//! on a runtime value has no entry here, so a layout obtained from this module
//! is complete by construction rather than by convention.

/// One field of a [`Wire::Struct`], in the order it appears on the wire.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Field {
    /// Mojang's own name for the field, from the record component or getter.
    pub name: &'static str,
    /// Layout of the field's value.
    pub wire: &'static Wire,
}

/// One constant of a [`Wire::Enum`], and the number it is sent as.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Constant {
    /// Mojang's own name for the constant.
    pub name: &'static str,
    /// The `VarInt` the server writes for it, which is the declaration index
    /// unless the class supplies ids of its own.
    pub value: i32,
}

/// The layout of a value on the wire.
///
/// Variants name what the server writes rather than how a Rust value is
/// shaped: a registry id and a plain `VarInt` are different variants because
/// they mean different things, while a signed and an unsigned 16-bit read are
/// the same two bytes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum Wire {
    /// Occupies no bytes.
    Unit,
    /// One byte, zero or one.
    Bool,
    /// Signed byte.
    I8,
    /// Big-endian signed 16-bit.
    I16,
    /// Big-endian unsigned 16-bit.
    U16,
    /// Big-endian signed 32-bit.
    I32,
    /// Big-endian signed 64-bit.
    I64,
    /// Big-endian IEEE 754 single.
    F32,
    /// Big-endian IEEE 754 double.
    F64,
    /// Variable-length signed 32-bit, seven bits per byte.
    VarInt,
    /// Variable-length signed 64-bit, seven bits per byte.
    VarLong,
    /// Two big-endian 64-bit halves, most significant first.
    Uuid,
    /// One 64-bit word packing x, z and y as 26, 26 and 12 bits.
    BlockPos,
    /// One 64-bit word packing two 32-bit chunk coordinates.
    ChunkPos,
    /// A block position, a face, three fractional offsets and two flags.
    BlockHitResult,
    /// A namespaced name written as a length-prefixed UTF-8 string.
    Identifier,
    /// A network NBT tag: a type byte then the payload, with no name.
    Nbt,
    /// A network NBT tag where `TAG_End` means the value is absent.
    OptionalNbt,
    /// A `VarInt` count, then that many big-endian 64-bit words.
    LongArray,
    /// A `VarInt` count, then that many `VarInt`s.
    VarIntArray,
    /// A `VarInt` byte count, then that many bytes.
    ByteArray {
        /// Largest byte count the server accepts.
        max: Option<u32>,
    },
    /// A `VarInt` length, then that many bytes of UTF-8.
    Str {
        /// Largest length the server accepts, in UTF-16 code units.
        max: Option<u32>,
    },
    /// A `VarInt` index into a synced registry.
    RegistryId {
        /// Registry the index is scoped to, e.g. `minecraft:item`.
        registry: &'static str,
    },
    /// A `VarInt`: zero then a tag name, otherwise a count plus one followed
    /// by that many registry ids.
    HolderSet {
        /// Registry the members belong to.
        registry: &'static str,
    },
    /// A `VarInt`: zero then an inline value, otherwise a registry id plus one.
    Holder {
        /// Registry the id is scoped to.
        registry: &'static str,
        /// Layout written when the value is inline rather than referenced.
        direct: &'static Self,
    },
    /// A boolean, then the value when it is present.
    Optional(&'static Self),
    /// A `VarInt` count, then that many elements.
    List {
        /// Layout of one element.
        element: &'static Self,
        /// Largest count the server accepts.
        max: Option<u32>,
    },
    /// A `VarInt` byte length, then the value within it.
    LengthPrefixed {
        /// Layout of the value inside the length.
        value: &'static Self,
        /// Largest byte length the server accepts.
        max: Option<u32>,
    },
    /// A `VarInt` count, then that many key and value pairs.
    Map {
        /// Layout of a key.
        key: &'static Self,
        /// Layout of a value.
        value: &'static Self,
    },
    /// A boolean selecting which of two layouts follows; true selects `left`.
    Either {
        /// Layout written when the discriminant is true.
        left: &'static Self,
        /// Layout written when the discriminant is false.
        right: &'static Self,
    },
    /// A `VarInt` naming one of a fixed set of constants.
    Enum {
        /// Class the constants come from, e.g.
        /// `net.minecraft.world.InteractionHand`.
        java_class: &'static str,
        /// Every constant, in declaration order.
        constants: &'static [Constant],
    },
    /// Fields written back to back with nothing between them.
    Struct(&'static [Field]),
    /// Bytes a hand-written codec in this crate owns.
    ///
    /// The extractor recognised the codec but its bytes are not a field list:
    /// `Vec3#LP_STREAM_CODEC` is one byte for a near-zero vector and six plus an
    /// optional `VarInt` otherwise. The layout is deliberately not described
    /// here, because describing it would be transcribing it, and a transcription
    /// that drifts from the codec is worse than an honest gap.
    Custom {
        /// Name shared with `CUSTOM_CODECS` in `nix/extract-protocol.py` and in
        /// `build.rs`, which is where the Rust implementation is named.
        codec: &'static str,
    },
}

impl Wire {
    /// Whether the layout is a single value with no nested structure.
    ///
    /// A scalar can be read and written without walking the tree, which is
    /// what most of an item's data components turn out to be.
    #[must_use]
    pub const fn is_scalar(&self) -> bool {
        !matches!(
            self,
            Self::Struct(_)
                | Self::List { .. }
                | Self::Map { .. }
                | Self::Either { .. }
                | Self::Optional(_)
                | Self::LengthPrefixed { .. }
                | Self::Holder { .. }
        )
    }
}
"""


def emit_wire(doc: dict, emitter: WireEmitter) -> str:
    v = doc["version"]
    return (
        HEADER.format(version=v["id"], protocol=v["protocolVersion"])
        + WIRE_PREAMBLE
        + "\n"
        + "\n".join(emitter.order)
    )


def emit_data_components(doc: dict, emitter: WireEmitter) -> str:
    """The data component registry: ids, names and value layouts.

    An `ItemStack` on the wire is an item id, a count and a patch over this
    registry, so every component's layout is part of the item layout. Ids come
    from Mojang's registry report and are cross-checked in the extractor
    against the order the server registers them in.
    """
    v = doc["version"]
    components = doc["dataComponents"]
    known = sum(1 for c in components if c["complete"])
    layouts = {
        c["name"]: emitter.reference(c["name"], c["wire"]) for c in components if c["complete"]
    }

    out = [HEADER.format(version=v["id"], protocol=v["protocolVersion"])]
    out.append("""
//! Data component types an item stack can carry.
//!
//! {known} of the {total} components have a layout the extractor could follow
//! to the bytes; the rest have codecs that branch on a runtime type, and
//! [`DataComponent::layout`] returns `None` for those rather than a guess.

/// A vanilla data component type.
///
/// Discriminants are the network ids from `minecraft:data_component_type`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
#[non_exhaustive]
pub enum DataComponent {{
""".format(known=known, total=len(components)))
    for index, c in enumerate(components):
        out.append("    /// `{}`\n".format(c["name"]))
        out.append("    {} = {},\n".format(pascal(c["name"]), index))
    out.append("}\n\n")

    out.append("impl DataComponent {\n")
    out.append("    /// Every component, in network id order.\n")
    out.append("    pub const ALL: &'static [Self] = &[\n")
    for c in components:
        out.append("        Self::{},\n".format(pascal(c["name"])))
    out.append("    ];\n\n")

    out.append("""    /// Numeric id as written on the wire.
    #[must_use]
    pub const fn to_raw(self) -> i32 {
        self as i32
    }

    /// Resolve an on-wire id, returning `None` for ids this version does not
    /// define.
    #[must_use]
    pub const fn from_raw(id: i32) -> Option<Self> {
        match id {
""")
    for index, c in enumerate(components):
        out.append("            {} => Some(Self::{}),\n".format(index, pascal(c["name"])))
    out.append("""            _ => None,
        }
    }

    /// Mojang resource name, e.g. `minecraft:custom_data`.
    #[must_use]
    pub const fn resource(self) -> &'static str {
        match self {
""")
    for c in components:
        out.append('            Self::{} => "{}",\n'.format(pascal(c["name"]), c["name"]))
    out.append("""        }
    }

    /// Layout of the component's value, or `None` where the server's own
    /// codec branches on a runtime type and no fixed layout exists.
    #[must_use]
    pub const fn layout(self) -> Option<&'static crate::generated::wire::Wire> {
        match self {
""")
    out.append(grouped_arms(
        [("Self::" + pascal(c["name"]), "Some({})".format(layouts[c["name"]]))
         for c in components if c["name"] in layouts],
        " " * 12))
    if len(layouts) != len(components):
        out.append("            _ => None,\n")
    out.append("""        }
    }

    /// Whether the value is a single scalar with no nested structure.
    ///
    /// False for components with no known layout as well as for structured
    /// ones, so a caller that only handles scalars can branch on this alone.
    #[must_use]
    pub const fn is_scalar(self) -> bool {
        match self.layout() {
            Some(wire) => wire.is_scalar(),
            None => false,
        }
    }
}
""")
    return "".join(out)


if __name__ == "__main__":
    raise SystemExit(main())
