"""Turn the registry dump into a Rust module.

The dump is one concatenated blob of network NBT per registry plus an index
naming each element and how many bytes it occupies. That shape survives into
Rust unchanged: the blob rides along as a file and `include_bytes!` puts it in
rodata, so encoding a `registry_data` packet is a memcpy of bytes Mojang's own
encoder produced rather than a re-serialisation of a parsed tree.
"""

import argparse
import json
import pathlib


HEADER = """// @generated by nix/generate-registry-data.py from Minecraft {version}.
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-registry-data

//! Contents of the registries a server has to send during configuration.
//!
//! [`crate::generated::registry`] carries the *names* in every vanilla
//! registry, which is all `reports/registries.json` knows. The registries in
//! this module are datapack-loaded, so their contents exist only once the game
//! has built them; these bytes come from running
//! `RegistrySynchronization.packRegistry` against the pinned server jar.
//!
//! Each element is laid out as `ByteBufCodecs.TAG` writes it -- a type byte
//! then the payload, with no root name -- so [`RegistryContents::encode`]
//! copies rather than re-encodes. A caller that wants to inspect or edit an
//! element can still decode one with [`crate::nbt::Tag`].
//!
//! The one departure from the server's own bytes is that every compound has
//! its keys sorted. `DimensionType` carries a map keyed on objects with
//! identity hash codes, so a server emits those entries in a different order
//! on every restart and these files would never have been reproducible.
//! An NBT compound is unordered, so a client reads the same element either
//! way.
//!
//! # What a client needs
//!
//! [`DIMENSION_TYPE`], [`WORLDGEN_BIOME`] and [`CHAT_TYPE`] are the three a
//! client cannot start without: `login` indexes into the first, chunk sections
//! into the second and every chat message into the third. The rest are sent
//! because a vanilla client validates that it received the full set.

use crate::{{Error, Result, Writer}};

/// Every registry a server sends during configuration, in the order
/// `RegistryDataLoader.SYNCHRONIZED_REGISTRIES` lists them.
pub static ALL: &[&RegistryContents] = &[
{all_entries}];

/// One synchronised registry and the contents of each of its elements.
#[derive(Debug, Clone, Copy)]
pub struct RegistryContents {{
    /// Registry name, e.g. `minecraft:dimension_type`.
    pub registry: &'static str,
    /// Element names in network-id order; the index is the id.
    pub ids: &'static [&'static str],
    /// Byte length of each element's NBT, parallel to [`ids`](Self::ids).
    pub lengths: &'static [u32],
    /// Every element's NBT, concatenated in the same order.
    pub payloads: &'static [u8],
}}

impl RegistryContents {{
    /// Number of elements.
    #[must_use]
    pub const fn len(&self) -> usize {{
        self.ids.len()
    }}

    /// True when the registry has no elements, which none of these do.
    #[must_use]
    pub const fn is_empty(&self) -> bool {{
        self.ids.is_empty()
    }}

    /// Walk the elements as `(name, network NBT)`.
    pub fn iter(&self) -> impl Iterator<Item = (&'static str, &'static [u8])> + '_ {{
        let mut offset = 0usize;
        self.ids.iter().zip(self.lengths).map(move |(id, length)| {{
            let length = *length as usize;
            let payload = &self.payloads[offset..offset + length];
            offset += length;
            (*id, payload)
        }})
    }}

    /// Look up one element's NBT by name.
    #[must_use]
    pub fn get(&self, name: &str) -> Option<&'static [u8]> {{
        self.iter()
            .find_map(|(id, payload)| (id == name).then_some(payload))
    }}

    /// Write the body of a `minecraft:registry_data` packet.
    ///
    /// Every element is written with its contents, which is the case where the
    /// client reported no known packs. A server that honoured
    /// `select_known_packs` would write a `false` in place of the payload for
    /// the elements the client already has; see
    /// [`crate::packets::configuration`].
    ///
    /// # Errors
    /// Returns [`Error::NegativeLength`] only for an element count a `VarInt`
    /// cannot describe, which no vanilla registry approaches.
    pub fn encode(&self, writer: &mut Writer) -> Result<()> {{
        writer.string(self.registry)?;
        writer.var_int(i32::try_from(self.len()).map_err(|_| Error::NegativeLength(-1))?);
        for (id, payload) in self.iter() {{
            writer.string(id)?;
            // `ByteBufCodecs.TAG.apply(ByteBufCodecs::optional)`: present, then
            // the tag bytes verbatim.
            writer.bool(true);
            writer.raw(payload);
        }}
        Ok(())
    }}
}}

/// Find a registry by name.
#[must_use]
pub fn by_name(name: &str) -> Option<&'static RegistryContents> {{
    ALL.iter()
        .copied()
        .find(|registry| registry.registry == name)
}}
"""


def rust_name(registry: str) -> str:
    """`minecraft:worldgen/biome` -> `WORLDGEN_BIOME`."""
    without_namespace = registry.split(":", 1)[-1]
    return without_namespace.replace("/", "_").upper()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dump", required=True, type=pathlib.Path)
    parser.add_argument("--version", required=True)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    args = parser.parse_args()

    index = json.loads((args.dump / "index.json").read_text())

    args.out.mkdir(parents=True, exist_ok=True)

    body = []
    all_entries = []
    for registry in index:
        name = registry["registry"]
        symbol = rust_name(name)
        blob = args.dump / registry["file"]
        (args.out / registry["file"]).write_bytes(blob.read_bytes())

        entries = registry["entries"]
        ids = "".join(f'        "{entry["id"]}",\n' for entry in entries)
        lengths = "".join(f"        {entry['length']},\n" for entry in entries)
        total = sum(entry["length"] for entry in entries)
        all_entries.append(f"    &{symbol},\n")

        body.append(
            f"/// `{name}` ({len(entries)} elements, {total} bytes of NBT).\n"
            f"pub static {symbol}: RegistryContents = RegistryContents {{\n"
            f'    registry: "{name}",\n'
            f"    ids: &[\n{ids}    ],\n"
            f"    lengths: &[\n{lengths}    ],\n"
            f'    payloads: include_bytes!("{registry["file"]}"),\n'
            f"}};\n"
        )

    text = HEADER.format(version=args.version, all_entries="".join(all_entries))
    text += "\n" + "\n".join(body)
    (args.out / "mod.rs").write_text(text)


if __name__ == "__main__":
    main()
