"""Generate the entity type table for hyperion-minecraft-proto.

`minecraft:entity_type` is a positional registry: the number `add_entity`
carries is the index of a type in it, so every id moves whenever Mojang inserts
one. A pig is 90 on 1.20.1 and 105 on 26.2, and nothing on the wire says which
numbering the sender meant, so a server holding the previous version's ids
spawns a different mob rather than failing.

Names are what survives a version bump, so each entry becomes an associated
constant rather than a row a caller looks up by string. That is the point of
generating this at all: naming `EntityType::PIG` at a call site turns a Mojang
rename into a compile error there, where a string would have turned it into a
`None` on whichever tick that entity happened to spawn.

The registry is read from the extracted `protocol.json` rather than from a
second pass over the jar, so this table and `generated/registry.rs` cannot
disagree about what the registry holds; `tests/entity_type.rs` checks they do
not.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

REGISTRY = "minecraft:entity_type"

# Every entry has to survive the conversion, or a name reaches Rust as an
# identifier that does not compile or that collides with another entry's.
IDENTIFIER = re.compile(r"^[A-Z][A-Z0-9_]*$")

HEADER = """\
// @generated by nix/generate-entity-types.py from Minecraft {version} (protocol {protocol}).
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-entity-types
"""

PREAMBLE = '''
//! Entity type network ids for Minecraft {version}.
//!
//! `{registry}` is positional, so the number `add_entity` carries is an index
//! into it and moves whenever Mojang inserts a type. A pig is 90 on 1.20.1 and
//! {pig} here. Nothing on the wire distinguishes the two, so a sender holding
//! the older numbering puts the wrong entity in the world rather than failing.
//!
//! The name is the part that survives a version bump, so a caller names the
//! type and this translates. Naming it through an associated constant rather
//! than through a string is what makes a rename a build failure:
//! [`EntityType::PIG`] stops existing, at the line that wanted a pig, rather
//! than [`entity_type`] quietly starting to return `None` at run time.

use crate::types::RegistryId;

/// One entry of `{registry}`, and the id this version sends for it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct EntityType {{
    name: &'static str,
    id: i32,
}}

impl EntityType {{
    /// Private so that the only values in existence are the table's own.
    const fn new(name: &'static str, id: i32) -> Self {{
        Self {{ name, id }}
    }}

    /// Namespaced name, e.g. `minecraft:pig`.
    #[must_use]
    pub const fn name(self) -> &'static str {{
        self.name
    }}

    /// Network id, which is what `add_entity` carries.
    #[must_use]
    pub const fn id(self) -> RegistryId {{
        RegistryId(self.id)
    }}
}}

/// How many entity types this version has, so every valid id is below this.
pub const ENTITY_TYPE_COUNT: usize = {count};

/// The entity type of that name, for a name only known at run time.
///
/// A name known at compile time should go through the constant of the same
/// name instead, so that a version bump dropping the type fails to build.
#[must_use]
pub fn entity_type(name: &str) -> Option<EntityType> {{
    // A scan rather than a binary search: the table is small, and the caller
    // is translating a name off the wire rather than doing this per tick.
    // Keeping the array in id order instead lets the id double as the index.
    ENTITY_TYPES.iter().copied().find(|entry| entry.name == name)
}}

/// Every entity type, in network-id order, so the index is the id.
pub static ENTITY_TYPES: &[EntityType] = &[
'''

CONSTANTS = """
// One constant per registry entry. Naming a type through one of these is what
// makes a version that renames or removes it fail to build.
impl EntityType {
"""


def identifier(name: str) -> str:
    """The constant name for a registry entry, or fail."""
    if not name.startswith("minecraft:"):
        raise SystemExit(
            f"{name} is not in the minecraft namespace, so the constant it would "
            "produce collides with any other namespace using the same path; teach "
            "this script a disambiguation before allowing it"
        )
    ident = name.removeprefix("minecraft:").upper()
    if not IDENTIFIER.match(ident):
        raise SystemExit(f"{name} does not convert to a Rust identifier ({ident!r})")
    return ident


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--protocol", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    doc = json.loads(args.protocol.read_text())
    registries = doc["registries"]
    if REGISTRY not in registries:
        raise SystemExit(
            f"{args.protocol} has no {REGISTRY}; the extractor stopped reporting "
            f"it, and {sorted(registries)[:4]}... is what it has"
        )
    entries = registries[REGISTRY]["entries"]

    idents = [identifier(name) for name in entries]
    duplicates = {i for i in idents if idents.count(i) > 1}
    if duplicates:
        raise SystemExit(f"two entries produce the same constant: {sorted(duplicates)}")

    # A registry the extractor truncated would otherwise emit a short table that
    # compiles and looks up nothing. These three are what every spawn path here
    # needs, so their absence is the cheapest proof the extraction went wrong.
    for required in ("minecraft:player", "minecraft:pig", "minecraft:item"):
        if required not in entries:
            raise SystemExit(f"{REGISTRY} is missing {required}, so the extraction is wrong")

    version = doc["version"]
    text = HEADER.format(version=version["id"], protocol=version["protocolVersion"])
    text += PREAMBLE.format(
        version=version["id"],
        registry=REGISTRY,
        count=len(entries),
        pig=entries.index("minecraft:pig"),
    )
    text += "".join(f"    EntityType::{ident},\n" for ident in idents)
    text += "];\n"

    text += CONSTANTS
    text += "".join(
        f"    /// `{name}` (id {index}).\n"
        f'    pub const {ident}: Self = Self::new("{name}", {index});\n'
        for index, (name, ident) in enumerate(zip(entries, idents))
    )
    text += "}\n"

    args.out.write_text(text)


if __name__ == "__main__":
    main()
