"""Generate the particle table for hyperion-minecraft-proto.

`minecraft:particle_type` is the one registry whose entries are not
interchangeable rows. `ParticleTypes.STREAM_CODEC` is a dispatch: a `VarInt`
id, and then whatever that id's own codec writes. 103 of the 125 types write
nothing at all; the other 22 write bodies of thirteen different shapes. Nothing
between the particle and the end of the frame is length-prefixed, so a type
sent with the wrong body does not lose a field, it shifts every byte after it.

That is why this registry is generated here rather than by the general registry
codegen, which emits an id-only enum per registry out of `protocol.json`.
`protocol.json` cannot express this one: `nix/extract-protocol.py` marks
`net.minecraft.core.particles.ParticleTypes#STREAM_CODEC` `unresolved`, because
following a dispatch needs the runtime type. So this script reads the dispatch
table out of the decompiled Java instead, where each `register` call names the
option class beside the particle, and reads each option class's own
`StreamCodec` to learn the body.

The two sources are held together by `particle_ids_match_the_registry` in the
generated file, which checks every id here against
`generated::registry::PARTICLE_TYPE`. That test is the only reason splitting
this registry off the general codegen is safe: without it, two spellings of one
table could drift and nothing would say so.

Anything in the Java this script does not already understand is a hard failure
rather than a skipped entry. A particle silently omitted would encode as some
other particle's id the next time the registry shifted, and a particle whose
body this got wrong would corrupt the rest of the frame. Neither is worth
trading for a run that finishes.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

REGISTRY = "minecraft:particle_type"
POSITION_SOURCE_REGISTRY = "minecraft:position_source_type"

# `ParticleTypes.register("name", overrideLimiter)` for a body-less type, and
# `register("name", overrideLimiter, <codec>, <streamCodec>)` for one with
# options. Only the option class matters here; the `codec` half is the JSON
# form, which never reaches the wire.
REGISTER = re.compile(
    r"public static final (?:SimpleParticleType|ParticleType<(?P<option>\w+)>) "
    r"(?P<constant>\w+) = ParticleTypes\.register\("
    r'"(?P<name>[a-z0-9_]+)", (?:true|false)(?P<tail>.*?)\);$'
)

# The stream codec of an option class, either as a static field or as the sole
# `return` of a `streamCodec(...)` factory.
STREAM_CODEC = re.compile(
    r"(?:STREAM_CODEC = |return )(?P<expr>StreamCodec\.composite\(.*"
    r"|ByteBufCodecs\.\w+(?:\(.*?\))?\.map\(.*"
    r"|\w+\.STREAM_CODEC\.map\(.*);$"
)

# A field name out of a getter: `o -> o.color`, `Type::getScale`,
# `Type::target`, or `o -> Float.valueOf(o.roll)`.
GETTER_FIELD = re.compile(r"(?:\.|::)(?:get)?(?P<field>[A-Za-z]\w*)\s*\)?\s*$")

# How each leaf codec is written, as (rust type, writer method, reader method).
# Anything absent is a codec this script has never seen and will not guess at.
PRIMITIVES = {
    # `ByteBufCodecs.INT` is a fixed four-byte big-endian int, not a VarInt.
    "ByteBufCodecs.INT": ("i32", "i32", "i32"),
    "ByteBufCodecs.VAR_INT": ("i32", "var_int", "var_int"),
    "ByteBufCodecs.FLOAT": ("f32", "f32", "f32"),
}

# Codecs whose type already exists in this crate and encodes itself. Written
# unqualified because the generated preamble imports every one of them; a
# qualified path here would leave that import unused and fail the build.
COMPOSITES = {
    "Vec3.STREAM_CODEC": "Vec3",
    "BlockPos.STREAM_CODEC": "BlockPos",
    "PositionSource.STREAM_CODEC": "PositionSource",
    "ItemStackTemplate.STREAM_CODEC": "ItemStackTemplate<'a>",
}

# `ByteBufCodecs.idMapper(<registry>)` is a bare VarInt index into a registry
# the client already has. Only the block state registry appears in a particle.
ID_MAPPERS = {
    "Block.BLOCK_STATE_REGISTRY": "BlockStateId",
}

# Fields whose `int` is a packed colour rather than a number. Vanilla writes
# both through the same `ByteBufCodecs.INT`, so only the name tells them apart,
# and a colour drawn as an integer is only ever noticed on a client.
COLOUR_FIELDS = {"color", "fromColor", "toColor"}

HEADER = """\
// @generated by nix/generate-particles.py from Minecraft {version} (protocol {protocol}).
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-particles
"""


def snake(name: str) -> str:
    """`arrivalInTicks` -> `arrival_in_ticks`."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def pascal(name: str) -> str:
    """`dust_color_transition` -> `DustColorTransition`."""
    return "".join(part.capitalize() for part in name.split("_"))


def split_args(text: str) -> list[str]:
    """Split a Java argument list on its top-level commas.

    A plain `text.split(",")` cuts inside `Either.right((Object)id)` and inside
    every lambda body, and the pieces then read as codecs that do not exist.
    """
    args, depth, start = [], 0, 0
    for index, char in enumerate(text):
        if char in "([":
            depth += 1
        elif char in ")]":
            depth -= 1
        elif char == "," and depth == 0:
            args.append(text[start:index].strip())
            start = index + 1
    args.append(text[start:].strip())
    return [arg for arg in args if arg]


def balanced(text: str, open_at: int) -> str:
    """The contents of the parenthesised group opening at `open_at`."""
    depth = 0
    for index in range(open_at, len(text)):
        if text[index] == "(":
            depth += 1
        elif text[index] == ")":
            depth -= 1
            if depth == 0:
                return text[open_at + 1:index]
    raise SystemExit(f"unbalanced parentheses in {text!r}")


def field_name(getter: str, option: str) -> str:
    """The field a getter reads, as a Rust identifier."""
    match = GETTER_FIELD.search(getter.strip())
    if not match:
        raise SystemExit(
            f"{option}: cannot tell which field {getter!r} reads; teach this "
            "script the shape before letting it name one"
        )
    return snake(match.group("field"))


class Field:
    """One value a particle's option class writes after the type id."""

    def __init__(self, name: str, rust: str, write: str, read: str) -> None:
        self.name = name
        self.rust = rust
        self.write = write
        self.read = read


def leaf(codec: str, name: str, option: str) -> tuple[str, str, str]:
    """The Rust type, write expression and read expression for one codec."""
    codec = codec.strip()
    if codec in PRIMITIVES:
        rust, write, read = PRIMITIVES[codec]
        if name in {snake(field) for field in COLOUR_FIELDS}:
            if write != "i32":
                raise SystemExit(f"{option}: colour field {name} is not an int")
            return ("Argb", "writer.i32({value}.to_bits());", "Argb::from_bits(reader.i32()?)")
        return (rust, f"writer.{write}(*{{value}});", f"reader.{read}()?")
    if codec.startswith("ByteBufCodecs.idMapper("):
        registry = balanced(codec, codec.index("(")).strip()
        if registry not in ID_MAPPERS:
            raise SystemExit(
                f"{option}: idMapper over {registry}, which this script has no "
                "Rust type for; add one to ID_MAPPERS with its wire form"
            )
        rust = ID_MAPPERS[registry]
        # `ByteBufCodecs.idMapper` is `ByteBufCodecs.VAR_INT.map(...)`: a bare
        # index into a registry the client already holds.
        return (rust, "writer.var_int({value}.to_raw());", f"{rust}::from_raw(reader.var_int()?)?")
    for suffix, rust in COMPOSITES.items():
        if codec.endswith(suffix):
            bare = rust.removesuffix("<'a>")
            if bare == "ItemStackTemplate":
                return (rust, "{value}.encode(writer)?;", f"{bare}::decode(reader, nbt)?")
            return (rust, "{value}.encode(writer)?;", f"{bare}::decode(reader)?")
    raise SystemExit(
        f"{option}: {codec!r} is a codec this script has never seen. Read its "
        "Java and add it to PRIMITIVES, COMPOSITES or ID_MAPPERS; guessing at "
        "a body shifts every byte after the particle."
    )


def parse_option(option: str, source: Path) -> list[Field]:
    """The fields an option class writes, read off its own `StreamCodec`."""
    text = source.read_text()
    matches = [STREAM_CODEC.search(line.strip()) for line in text.splitlines()]
    found = [match.group("expr") for match in matches if match]
    if not found:
        raise SystemExit(f"{option}: no stream codec in {source}")
    expr = found[0]

    if expr.startswith("StreamCodec.composite("):
        args = split_args(balanced(expr, expr.index("(")))
        # `composite(codec, getter, codec, getter, ..., constructor)`, so an
        # even count means one of the pairs is not a pair.
        if len(args) % 2 != 1:
            raise SystemExit(f"{option}: composite has {len(args)} arguments, expected an odd count")
        pairs = [(args[i], args[i + 1]) for i in range(0, len(args) - 1, 2)]
    else:
        # `<codec>.map(fromWire, toWire)`: one field, and the second argument
        # is the getter that names it.
        head, _, tail = expr.rpartition(".map(")
        args = split_args(balanced("(" + tail, 0))
        if len(args) != 2:
            raise SystemExit(f"{option}: map has {len(args)} arguments, expected 2")
        pairs = [(head, args[1])]

    fields = []
    for codec, getter in pairs:
        name = field_name(getter, option)
        rust, write, read = leaf(codec, name, option)
        fields.append(Field(name, rust, write, read))
    names = [field.name for field in fields]
    if len(set(names)) != len(names):
        raise SystemExit(f"{option}: two fields named the same: {names}")
    return fields


PREAMBLE = '''
//! Particle types for Minecraft {version}, and the options each one carries.
//!
//! `ParticleTypes.STREAM_CODEC` is `ByteBufCodecs.registry(PARTICLE_TYPE)
//! .dispatch(ParticleOptions::getType, ParticleType::streamCodec)`: a `VarInt`
//! id, then whatever that id's own codec writes. [`Particle`] is that pair as
//! one closed value, so a caller cannot name a type and forget its body.
//!
//! There is no `Particle::from_id`. A type id alone does not say how many
//! bytes follow it, so turning one back into a particle means reading the
//! body, which is [`Particle::decode`]. [`ParticleKind`] is the id on its own,
//! for the cases that really do only want the number or the name.
//!
//! Both enums are closed and neither has an `Unknown` variant. A type this
//! server never sends is also a type whose body length it does not know, and
//! nothing after the particle is length-prefixed, so there is nothing to skip
//! past: the read has to stop rather than resynchronise on the next field.
//!
//! # Why this registry is generated apart from the others
//!
//! The general registry codegen emits one id-only enum per registry out of
//! `protocol.json`, and it deliberately skips `{registry}`. That
//! file cannot express this one: the extractor marks
//! `ParticleTypes#STREAM_CODEC` `unresolved`, because following a dispatch
//! needs the runtime type, so all it carries for particles is the names.
//! `nix/generate-particles.py` reads the dispatch table out of the decompiled
//! Java instead, which is the only place that says which of the 125 entries
//! carry a payload and what shape it is.
//!
//! **Do not re-add `{registry}` to the general codegen.** Two
//! spellings of one registry can drift, and a drifted particle id draws the
//! wrong particle rather than failing. What makes the split safe is
//! `particle_ids_match_the_registry` below, which holds every id here against
//! `generated::registry::PARTICLE_TYPE`.

use crate::{{
    Decode, Encode, Error, Reader, Result, Writer,
    item::{{ItemStackTemplate, nbt::NbtScan}},
    types::{{BlockPos, BlockStateId, Vec3}},
}};

/// A packed ARGB colour, as a particle option carries it.
///
/// Vanilla writes this through the same `ByteBufCodecs.INT` it writes a count
/// with, so only the field name distinguishes the two in the Java. Giving it a
/// type here is what stops a caller passing a particle count where a colour
/// goes, which is a mistake only a client ever sees.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Argb(i32);

impl Argb {{
    /// A colour from its four channels.
    #[must_use]
    pub const fn new(alpha: u8, red: u8, green: u8, blue: u8) -> Self {{
        Self(
            ((alpha as i32) << 24)
                | ((red as i32) << 16)
                | ((green as i32) << 8)
                | (blue as i32),
        )
    }}

    /// A fully opaque colour.
    #[must_use]
    pub const fn opaque(red: u8, green: u8, blue: u8) -> Self {{
        Self::new(0xff, red, green, blue)
    }}

    /// The packed value exactly as the wire holds it.
    #[must_use]
    pub const fn from_bits(bits: i32) -> Self {{
        Self(bits)
    }}

    /// The packed value exactly as the wire holds it.
    #[must_use]
    pub const fn to_bits(self) -> i32 {{
        self.0
    }}

    /// Alpha, red, green, blue.
    ///
    /// Big-endian bytes rather than shifts: the wire writes this `int` big
    /// endian, so the byte order already is the channel order.
    #[must_use]
    pub const fn channels(self) -> [u8; 4] {{
        self.0.to_be_bytes()
    }}
}}
'''

POSITION_SOURCE = '''
/// Where a vibration is travelling to (`PositionSource`).
///
/// Another registry dispatch, over `{registry}`, which has exactly
/// the two entries below. A third would land here as a build failure in
/// `nix/generate-particles.py` rather than as a wrong body on the wire.
#[derive(Debug, Clone, Copy, PartialEq)]
#[repr(u16)]
pub enum PositionSource {{
{variants}}}

impl PositionSource {{
    /// The `{registry}` id this variant is dispatched on.
    #[must_use]
    pub const fn id(&self) -> u16 {{
        match self {{
{ids}        }}
    }}
}}

impl Encode for PositionSource {{
    fn encode(&self, writer: &mut Writer) -> Result<()> {{
        writer.var_int(i32::from(self.id()));
        match self {{
{encode}        }}
        Ok(())
    }}
}}

impl Decode<'_> for PositionSource {{
    fn decode(reader: &mut Reader<'_>) -> Result<Self> {{
        let id = reader.var_int()?;
        match id {{
{decode}            value => Err(Error::InvalidEnum {{
                name: "PositionSource",
                value,
            }}),
        }}
    }}
}}
'''


TESTS = '''
#[cfg(test)]
mod tests {{
    use super::{{Particle, ParticleKind, PARTICLE_NAMES}};
    use crate::generated::registry::PARTICLE_TYPE;

    /// The reason this table may live apart from `generated/registry.rs`.
    ///
    /// Two spellings of one registry can drift, and a particle id that has
    /// drifted draws the wrong particle rather than failing, so nothing would
    /// report it. This is what makes the split safe.
    #[test]
    fn particle_ids_match_the_registry() {{
        for kind in ParticleKind::ALL {{
            assert_eq!(
                PARTICLE_TYPE.id_of(kind.name()),
                Some(kind.id() as usize),
                "{{}} is id {{}} here",
                kind.name(),
                kind.id(),
            );
        }}
    }}

    /// A truncated table would compile and silently lack whatever Mojang added
    /// last, which is the end of the registry and so the highest ids.
    #[test]
    fn every_registry_entry_has_a_variant() {{
        assert_eq!(ParticleKind::ALL.len(), PARTICLE_TYPE.entries.len());
        assert_eq!(PARTICLE_NAMES.len(), PARTICLE_TYPE.entries.len());
    }}

    #[test]
    fn kind_round_trips_through_its_id_and_name() {{
        for kind in ParticleKind::ALL {{
            assert_eq!(ParticleKind::from_id(kind.id()), Some(*kind));
            assert_eq!(ParticleKind::from_name(kind.name()), Some(*kind));
        }}
        assert_eq!(ParticleKind::from_id({count}), None);
        assert_eq!(ParticleKind::from_name("minecraft:not_a_particle"), None);
    }}

    /// The payload enum and the id-only enum have to agree, or a caller that
    /// matched on one and sent the other would send a different particle.
    #[test]
    fn a_body_less_particle_and_its_kind_share_an_id() {{
        assert_eq!(Particle::Flame.kind(), ParticleKind::Flame);
        assert_eq!(Particle::Flame.id(), ParticleKind::Flame.id());
        assert_eq!(Particle::Flame.name(), ParticleKind::Flame.name());
    }}
}}
'''


def emit(entries, particles, version, protocol, position_sources) -> str:
    """The whole generated file."""
    text = HEADER.format(version=version["id"], protocol=version["protocolVersion"])
    text += PREAMBLE.format(version=version["id"], registry=REGISTRY)
    text += position_sources

    # --- ParticleKind, the id on its own -----------------------------------
    text += """
/// A particle type, without its options.
///
/// The discriminant is the `minecraft:particle_type` id, so [`id`](Self::id)
/// is a move rather than a table lookup. Registry ids are positional and shift
/// whenever Mojang inserts a type, which is why they are generated rather than
/// written down.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum ParticleKind {
"""
    for index, particle in enumerate(particles):
        text += f"    /// `{entries[index]}`.\n"
        text += f"    {particle['variant']} = {index},\n"
    text += "}\n"

    text += "\nimpl ParticleKind {\n    /// Every type, in id order, so the index is the id.\n"
    text += "    pub const ALL: &'static [Self] = &[\n"
    text += "".join(f"        Self::{p['variant']},\n" for p in particles)
    text += "    ];\n"
    text += """
    /// The `minecraft:particle_type` id.
    #[must_use]
    pub const fn id(self) -> u16 {
        self as u16
    }

    /// The namespaced registry name, e.g. `minecraft:flame`.
    #[must_use]
    pub const fn name(self) -> &'static str {
        PARTICLE_NAMES[self as usize]
    }

    /// The type an id off the wire names, if this version has one.
    ///
    /// The decode boundary and nowhere else: a type named in source goes
    /// through the variant, so a version that drops it fails to build.
    #[must_use]
    pub const fn from_id(id: u16) -> Option<Self> {
        match id {
"""
    for index, particle in enumerate(particles):
        text += f"            {index} => Some(Self::{particle['variant']}),\n"
    text += """            _ => None,
        }
    }

    /// The type of that namespaced name, if this version has one.
    #[must_use]
    pub fn from_name(name: &str) -> Option<Self> {
        // A scan rather than a map: the table is small and this runs when a
        // name arrives from outside, not per tick.
        let index = PARTICLE_NAMES.iter().position(|entry| *entry == name)?;
        Self::from_id(u16::try_from(index).ok()?)
    }
}

/// Every registry name, in id order.
"""
    text += f"static PARTICLE_NAMES: [&str; {len(entries)}] = [\n"
    text += "".join(f'    "{name}",\n' for name in entries)
    text += "];\n"
    return text


def emit_particle(entries, particles) -> str:
    """The payload enum: a type together with whatever its codec writes."""
    text = """
/// A particle type together with the options its own codec writes.
///
/// One value rather than a type beside a body, because the two are not
/// independent: the id decides how many bytes follow, and nothing after them
/// is length-prefixed. A `Dust` sent without its colour and scale does not
/// draw a colourless dust, it desynchronises the rest of the frame.
#[derive(Debug, Clone, PartialEq)]
#[repr(u16)]
pub enum Particle<'a> {
"""
    for index, particle in enumerate(particles):
        note = (
            f"a `{particle['option']}`." if particle["option"] else "no options."
        )
        text += f"    /// `{entries[index]}`, {note}\n"
        if particle["fields"]:
            text += f"    {particle['variant']} {{\n"
            for field in particle["fields"]:
                text += f"        /// `{particle['option']}.{field.name}`.\n"
                text += f"        {field.name}: {field.rust},\n"
            text += f"    }} = {index},\n"
        else:
            text += f"    {particle['variant']} = {index},\n"
    text += "}\n"

    # --- kind / id / name --------------------------------------------------
    text += """
impl Particle<'_> {
    /// The type, without its options.
    #[must_use]
    pub const fn kind(&self) -> ParticleKind {
        match self {
"""
    for particle in particles:
        pattern = f"Self::{particle['variant']}"
        if particle["fields"]:
            pattern += " { .. }"
        text += f"            {pattern} => ParticleKind::{particle['variant']},\n"
    text += """        }
    }

    /// The `minecraft:particle_type` id.
    #[must_use]
    pub const fn id(&self) -> u16 {
        self.kind().id()
    }

    /// The namespaced registry name, e.g. `minecraft:flame`.
    #[must_use]
    pub const fn name(&self) -> &'static str {
        self.kind().name()
    }
}
"""

    # --- Encode ------------------------------------------------------------
    bare = [p for p in particles if not p["fields"]]
    text += """
impl Encode for Particle<'_> {
    fn encode(&self, writer: &mut Writer) -> Result<()> {
        writer.var_int(i32::from(self.id()));
        match self {
"""
    if bare:
        arms = "\n            | ".join(f"Self::{p['variant']}" for p in bare)
        text += f"            {arms} => {{}}\n"
    # Grouped by option class, because several particles share one class and so
    # write an identical body, and two identical match arms are a lint.
    grouped: dict[str, list[dict]] = {}
    for particle in particles:
        if particle["fields"]:
            grouped.setdefault(particle["option"], []).append(particle)
    for group in grouped.values():
        fields = group[0]["fields"]
        names = ", ".join(field.name for field in fields)
        arms = "\n            | ".join(
            f"Self::{particle['variant']} {{ {names} }}" for particle in group
        )
        text += f"            {arms} => {{\n"
        for field in fields:
            text += "                " + field.write.format(value=field.name) + "\n"
        text += "            }\n"
    text += """        }
        Ok(())
    }
}
"""

    # --- decode ------------------------------------------------------------
    text += """
impl<'a> Particle<'a> {
    /// Read a particle and whatever its type's codec wrote after the id.
    ///
    /// Not a [`Decode`] impl, because one variant carries an item stack and a
    /// stack's component values can only be measured with an NBT scanner. Same
    /// shape as [`crate::packets::play::SetEquipment::decode`], for the same
    /// reason.
    ///
    /// # Errors
    /// [`Error::InvalidEnum`] for a type this version does not have. There is
    /// no recovery from that: the id is what says how long the body is, so an
    /// unknown one leaves nothing to skip.
    pub fn decode(reader: &mut Reader<'a>, nbt: &impl NbtScan) -> Result<Self> {
        let id = reader.var_int()?;
        match id {
"""
    for index, particle in enumerate(particles):
        if not particle["fields"]:
            text += f"            {index} => Ok(Self::{particle['variant']}),\n"
            continue
        text += f"            {index} => Ok(Self::{particle['variant']} {{\n"
        for field in particle["fields"]:
            text += f"                {field.name}: {field.read},\n"
        text += "            }),\n"
    text += """            value => Err(Error::InvalidEnum {
                name: "Particle",
                value,
            }),
        }
    }
}
"""
    text += TESTS.format(count=len(entries))
    return text


def find_class(sources: Path, name: str) -> Path:
    """The one decompiled source file for a Java class."""
    found = sorted(sources.rglob(f"{name}.java"))
    if len(found) != 1:
        raise SystemExit(
            f"{name}.java matched {len(found)} files under {sources}; the "
            "decompiled subset changed and this script is reading the wrong one"
        )
    return found[0]


def emit_position_source(sources: Path, entries: list[str]) -> str:
    """The `PositionSource` dispatch, from the two classes the registry names."""
    known = {"minecraft:block": "BlockPositionSource", "minecraft:entity": "EntityPositionSource"}
    if entries != list(known):
        raise SystemExit(
            f"{POSITION_SOURCE_REGISTRY} is {entries}, not {list(known)}; a "
            "vibration's body changed shape and this script cannot guess the "
            "new one"
        )
    variants, ids, encode, decode = "", "", "", ""
    for index, (entry, klass) in enumerate(known.items()):
        variant = pascal(entry.removeprefix("minecraft:"))
        fields = parse_option(klass, find_class(sources, klass))
        variants += f"    /// `{entry}` (`{klass}`).\n    {variant} {{\n"
        for field in fields:
            variants += f"        /// `{klass}.{field.name}`.\n"
            variants += f"        {field.name}: {field.rust},\n"
        variants += f"    }} = {index},\n"
        ids += f"            Self::{variant} {{ .. }} => {index},\n"
        names = ", ".join(field.name for field in fields)
        encode += f"            Self::{variant} {{ {names} }} => {{\n"
        for field in fields:
            encode += "                " + field.write.format(value=field.name) + "\n"
        encode += "            }\n"
        decode += f"            {index} => Ok(Self::{variant} {{\n"
        for field in fields:
            decode += f"                {field.name}: {field.read},\n"
        decode += "            }),\n"
    return POSITION_SOURCE.format(
        registry=POSITION_SOURCE_REGISTRY,
        variants=variants,
        ids=ids,
        encode=encode,
        decode=decode,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--protocol", required=True, type=Path)
    parser.add_argument("--sources", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    doc = json.loads(args.protocol.read_text())
    registries = doc["registries"]
    for required in (REGISTRY, POSITION_SOURCE_REGISTRY):
        if required not in registries:
            raise SystemExit(f"{args.protocol} has no {required}")
    entries = registries[REGISTRY]["entries"]

    # The registry is the authority on which particles exist and what their ids
    # are; the Java is the authority on what each one writes. Reading the ids
    # off the registry rather than off the declaration order in the Java is
    # what lets the two disagree loudly instead of quietly.
    bodies = {}
    java = find_class(args.sources, "ParticleTypes").read_text()
    for line in java.splitlines():
        match = REGISTER.search(line.strip())
        if not match:
            continue
        name = f"minecraft:{match.group('name')}"
        if name in bodies:
            raise SystemExit(f"{name} is registered twice")
        option = match.group("option")
        bodies[name] = option

    missing = [name for name in entries if name not in bodies]
    if missing:
        raise SystemExit(
            f"{len(missing)} registry entries have no register() call in "
            f"ParticleTypes.java, starting with {missing[:4]}; the regex no "
            "longer matches every declaration"
        )
    extra = [name for name in bodies if name not in entries]
    if extra:
        raise SystemExit(f"ParticleTypes.java registers {extra}, which the registry does not list")

    parsed: dict[str, list[Field]] = {}
    particles = []
    for name in entries:
        option = bodies[name]
        if option is not None and option not in parsed:
            parsed[option] = parse_option(option, find_class(args.sources, option))
        particles.append(
            {
                "variant": pascal(name.removeprefix("minecraft:")),
                "option": option,
                "fields": parsed[option] if option else [],
            }
        )

    variants = [particle["variant"] for particle in particles]
    if len(set(variants)) != len(variants):
        raise SystemExit("two registry entries produce the same variant name")

    # A registry the extractor truncated would emit a short table that compiles
    # and draws the wrong thing. These four are what the effects layer is built
    # on, and one of each body shape, so their absence is the cheapest proof
    # the extraction went wrong.
    for required in ("minecraft:flame", "minecraft:dust", "minecraft:block", "minecraft:item"):
        if required not in entries:
            raise SystemExit(f"{REGISTRY} is missing {required}, so the extraction is wrong")

    position_sources = emit_position_source(
        args.sources, registries[POSITION_SOURCE_REGISTRY]["entries"]
    )
    text = emit(entries, particles, doc["version"], doc["version"], position_sources)
    text += emit_particle(entries, particles)
    args.out.write_text(text)


if __name__ == "__main__":
    main()
