"""Generate the block state table for hyperion-minecraft-proto.

`reports/blocks.json` lists all 32366 states one by one, which is thirty times
more rows than a table needs. Two facts about the data collapse it:

* every block's state ids are contiguous, so a block needs one base id rather
  than one id per state, and
* every block's states are the cartesian product of its properties with the
  last property varying fastest, so the offset within that run is a mixed-radix
  index over the property values.

Neither fact is documented by Mojang, so both are re-derived and re-checked
here against every state on every run. A version that broke either would
otherwise produce a table that is wrong rather than one that fails to build.

The property order the product uses is *not* always the order `blocks.json`
declares. It is recovered from the state list instead: the distance to the
first state that changes a property is that property's stride, and sorting by
descending stride gives the enumeration order.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = """\
// @generated by nix/generate-block-states.py from Minecraft {version} (protocol {protocol}).
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-block-states
"""

PREAMBLE = '''
//! Block state network ids for Minecraft {version}.
//!
//! A block state is a block plus a value for each of its properties, and the
//! wire carries it as a single number: the index of that state in one global
//! registry of all {states} of them. The numbering is dense but arbitrary, so
//! it moves with almost every game version, and a world stored against an
//! older one has to be translated through names rather than through ids.
//!
//! [`state_id`] is that translation. It takes a block name and any subset of
//! its properties, in any order, and returns the id this protocol version
//! sends.
//!
//! # How {blocks} rows describe {states} states
//!
//! Each block owns a contiguous run of ids, and the states inside that run are
//! the cartesian product of its properties with the last property varying
//! fastest. So a block is a base id plus its properties in enumeration order,
//! and the offset into the run is a mixed-radix index.
//!
//! That enumeration order is not always the order the game *declares* the
//! properties in -- {permuted} blocks differ, `minecraft:chest` among them,
//! which declares `[type, facing, waterlogged]` and enumerates
//! `[facing, type, waterlogged]`. The order here is the enumerated one,
//! recovered from the states themselves, so indexing with it is correct for
//! every block rather than for most of them.

/// One property of a block, and the values it takes in enumeration order.
#[derive(Debug, Clone, Copy)]
pub struct Property {{
    /// Property name, e.g. `facing`.
    pub name: &'static str,
    /// Values in the order the ids enumerate them; the index is the digit.
    pub values: &'static [&'static str],
}}

/// One block, and the run of state ids it owns.
#[derive(Debug, Clone, Copy)]
pub struct Block {{
    /// Namespaced block name, e.g. `minecraft:oak_stairs`.
    pub name: &'static str,
    /// Network id of this block's first state.
    pub base_id: u32,
    /// Network id of the state placing this block gives by default.
    pub default_id: u32,
    /// How many states this block has; its ids are `base_id .. base_id + this`.
    pub state_count: u32,
    /// Properties in enumeration order, the last varying fastest.
    pub properties: &'static [Property],
}}

impl Block {{
    /// Network id of the state matching `properties`.
    ///
    /// Order does not matter. A property this block does not have, or a value
    /// it does not take, returns `None`: the caller is translating between two
    /// versions whose property sets differ, and quietly ignoring the part that
    /// did not match would hand back a plausible id for the wrong state.
    ///
    /// A property this block *does* have but the caller left out takes its
    /// value from [`default_id`](Self::default_id)'s state, which is how a
    /// property newer than the caller's version resolves.
    #[must_use]
    pub fn state_id(&self, properties: &[(&str, &str)]) -> Option<u32> {{
        let default_offset = self.default_id - self.base_id;
        let mut stride = self.state_count;
        let mut offset = 0;
        let mut used = 0usize;

        for property in self.properties {{
            let radix = u32::try_from(property.values.len()).ok()?;
            // Walking the properties in order divides the stride down from the
            // whole run to this property's own step.
            stride /= radix;

            let given = properties
                .iter()
                .find(|(name, _)| *name == property.name)
                .map(|(_, value)| *value);
            let digit = match given {{
                Some(value) => {{
                    used += 1;
                    let index = property.values.iter().position(|v| *v == value)?;
                    u32::try_from(index).ok()?
                }}
                None => (default_offset / stride) % radix,
            }};
            offset += digit * stride;
        }}

        // Every argument has to have been consumed, or the caller named a
        // property this block does not have -- or named one of them twice.
        (used == properties.len()).then_some(self.base_id + offset)
    }}

    /// This block's property of that name, if it has one.
    #[must_use]
    pub fn property(&self, name: &str) -> Option<&'static Property> {{
        self.properties.iter().find(|property| property.name == name)
    }}
}}

/// State id of `minecraft:air`, which is what an empty chunk section is full of.
pub const AIR: u32 = {air};

/// How many block states exist, so every valid id is below this.
pub const STATE_COUNT: u32 = {states};

/// Look up a block by its namespaced name, e.g. `minecraft:oak_stairs`.
#[must_use]
pub fn block(name: &str) -> Option<&'static Block> {{
    BLOCKS
        .binary_search_by(|candidate| candidate.name.cmp(name))
        .ok()
        .map(|index| &BLOCKS[index])
}}

/// Network id of `name` in the state matching `properties`.
///
/// See [`Block::state_id`] for how a partial or mismatched property list is
/// treated. Returns `None` for a block this version does not have.
#[must_use]
pub fn state_id(name: &str, properties: &[(&str, &str)]) -> Option<u32> {{
    block(name)?.state_id(properties)
}}

/// Network id of the state placing `name` gives by default.
#[must_use]
pub fn default_state_id(name: &str) -> Option<u32> {{
    Some(block(name)?.default_id)
}}

/// Every block, sorted by name so [`block`] can binary search.
pub static BLOCKS: &[Block] = &[
'''


def enumeration_order(name: str, properties: dict, states: list) -> list[str]:
    """Recover the order the states enumerate the properties in.

    In a mixed-radix product the distance from the first state to the first one
    that changes a given property is that property's stride, and strides are
    strictly decreasing along the enumeration order.
    """
    if not properties:
        return []

    first = states[0]["properties"]
    strides = {}
    for prop in properties:
        stride = next(
            (i for i, state in enumerate(states) if state["properties"][prop] != first[prop]),
            None,
        )
        if stride is None:
            raise SystemExit(
                f"{name}.{prop} never changes across {len(states)} states, so its "
                "position in the enumeration cannot be recovered"
            )
        strides[prop] = stride
    return sorted(properties, key=lambda prop: -strides[prop])


def check_block(name: str, block: dict) -> tuple[list[str], int, int]:
    """Re-derive the two facts the table depends on, or fail.

    Returns the enumeration order, the base id, and the default state's id.
    """
    properties = block.get("properties", {})
    states = block["states"]

    ids = [state["id"] for state in states]
    base = min(ids)
    if ids != list(range(base, base + len(ids))):
        raise SystemExit(
            f"{name} has non-contiguous state ids ({base}..{max(ids)} over "
            f"{len(ids)} states), which a base id cannot describe"
        )

    size = 1
    for values in properties.values():
        if len(values) != len(set(values)):
            raise SystemExit(f"{name} repeats a value in one of its properties")
        size *= len(values)
    if size != len(states):
        raise SystemExit(
            f"{name} has {len(states)} states but its properties describe a "
            f"product of {size}, so the states are not a cartesian product"
        )

    order = enumeration_order(name, properties, states)

    # The strides only prove the order is consistent with the first state.
    # Recomputing every state's index from scratch is what proves the whole run.
    for index, state in enumerate(states):
        computed = 0
        for prop in order:
            computed = computed * len(properties[prop]) + properties[prop].index(
                state["properties"][prop]
            )
        if computed != index:
            raise SystemExit(
                f"{name} state {state['id']} ({state['properties']}) lands at "
                f"index {computed} rather than {index} under the recovered "
                f"order {order}"
            )

    defaults = [state["id"] for state in states if state.get("default")]
    if len(defaults) != 1:
        raise SystemExit(f"{name} has {len(defaults)} default states, expected exactly 1")

    return order, base, defaults[0]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blocks", required=True, type=Path)
    parser.add_argument("--version", required=True)
    parser.add_argument("--protocol", required=True)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    data = json.loads(args.blocks.read_text())

    rows = []
    seen = set()
    permuted = 0
    for name in sorted(data):
        block = data[name]
        order, base, default = check_block(name, block)
        properties = block.get("properties", {})
        if order != list(properties):
            permuted += 1

        count = len(block["states"])
        overlap = seen.intersection(range(base, base + count))
        if overlap:
            raise SystemExit(f"{name} reuses state ids already taken: {sorted(overlap)[:8]}")
        seen.update(range(base, base + count))

        emitted = "".join(
            '            Property {{ name: "{}", values: &[{}] }},\n'.format(
                prop, ", ".join(f'"{value}"' for value in properties[prop])
            )
            for prop in order
        )
        rows.append(
            f"    Block {{\n"
            f'        name: "{name}",\n'
            f"        base_id: {base},\n"
            f"        default_id: {default},\n"
            f"        state_count: {count},\n"
            f"        properties: &[\n{emitted}        ],\n"
            f"    }},\n"
        )

    total = len(seen)
    if seen != set(range(total)):
        raise SystemExit(
            f"block state ids are not dense: {total} ids spanning "
            f"0..{max(seen)}, so some id belongs to no block"
        )

    air = data["minecraft:air"]["states"][0]["id"]
    if air != 0:
        raise SystemExit(f"minecraft:air is state {air}, not 0")

    text = HEADER.format(version=args.version, protocol=args.protocol)
    text += PREAMBLE.format(
        version=args.version,
        blocks=len(data),
        states=total,
        permuted=permuted,
        air=air,
    )
    text += "".join(rows)
    text += "];\n"
    args.out.write_text(text)


if __name__ == "__main__":
    main()
