"""Generate the block collision shape table for hyperion-minecraft-proto.

The input is `collision-shapes.json`, which `nix/java/VanillaShapes.java` reads
out of the server jar by calling `getCollisionShape` on every state. See that
file for why the game itself is the only source: a collision shape is a
`VoxelShape` constant compiled into a block class, and Mojang's data generator
does not carry it.

Two arrays come out. `SHAPES` holds each distinct box list once, because 32366
states share 326 shapes -- every full cube is the same unit box whatever block
it belongs to. `STATE_SHAPES` is one index per state id, so a lookup is two
loads and no search.

Every coordinate the game produces is a multiple of 1/32, so writing them as
`f32` is exact rather than rounded. That is re-checked on every run: a version
introducing a finer coordinate fails the build instead of quietly moving a
block surface.
"""

from __future__ import annotations

import argparse
import json
import re
import struct
import textwrap
from pathlib import Path

HEADER = """\
// @generated by nix/generate-collision-shapes.py from Minecraft {version} (protocol {protocol}).
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-collision-shapes
"""

PREAMBLE = '''
//! Block collision shapes for Minecraft {version}.
//!
//! What an entity stops against. A block state's shape is a list of
//! axis-aligned boxes in the block's own coordinates, where a full cube is
//! `[0, 0, 0, 1, 1, 1]` and a bottom slab is `[0, 0, 0, 1, 0.5, 1]`; a state
//! with no boxes at all -- air, a torch, tall grass -- is passed through.
//!
//! The table is read out of the server jar rather than out of Mojang's data
//! generator, which describes a state as an id and a property map and stops
//! there. A collision shape is a `VoxelShape` constant compiled into each
//! block class, so the only thing that can answer is the running game:
//! `nix/java/VanillaShapes.java` calls `getCollisionShape` on all {states} of
//! them, and this file is what it said.
//!
//! # {shape_count} shapes for {states} states
//!
//! Distinct box lists are stored once in [`SHAPES`] and [`STATE_SHAPES`] gives
//! each state's index into it, because the states repeat themselves heavily:
//! {full_cube} of them are the same unit cube and {empty} have no boxes at
//! all. So a lookup is two loads and no search, and the table holds {boxes}
//! boxes rather than {total_boxes}.
//!
//! # Precision
//!
//! The game computes these as `double`s, and every value it produces is a
//! multiple of 1/32, so all {distinct} of them are exactly representable in
//! `f32` and this table loses nothing by storing them that way. The generator
//! re-checks that on every run, so a version introducing a coordinate that
//! needs more precision fails the build rather than rounding it silently.

/// One collision box, in the block's own coordinates:
/// `[min_x, min_y, min_z, max_x, max_y, max_z]`.
///
/// A few shapes reach outside the unit cube -- a wall's post is 1.5 high and a
/// big dripleaf's stem starts at -0.25 -- so a consumer that assumes `0..=1`
/// is assuming something the game does not.
pub type CollisionBox = [f32; 6];

/// The collision boxes of the block state with network id `state_id`.
///
/// `None` for an id this version does not have. For a caller holding an id
/// from [`crate::block_state`] that cannot happen, and would mean the two
/// tables came from different jars.
#[must_use]
pub fn collision_shape(state_id: u32) -> Option<&'static [CollisionBox]> {{
    let index = usize::try_from(state_id).ok()?;
    let shape = *STATE_SHAPES.get(index)?;
    Some(SHAPES[usize::from(shape)])
}}

// The two tables describe one registry read out of one jar, so a disagreement
// about how many states it has means one of them was regenerated and the other
// was not.
const _: () = assert!(
    STATE_SHAPES.len() == crate::block_state::STATE_COUNT as usize,
    "the collision shape table and the block state table disagree about how many states exist"
);

/// Every distinct box list, referenced by index from [`STATE_SHAPES`].
pub static SHAPES: &[&[CollisionBox]] = &[
{shape_table}];

/// Every state's index into [`SHAPES`], indexed by network id.
pub static STATE_SHAPES: &[u16] = &[
{state_table}];
'''


def number(value: float) -> str:
    """A Rust `f32` literal that round-trips to exactly `value`."""
    if struct.unpack("f", struct.pack("f", value))[0] != value:
        raise SystemExit(
            f"{value!r} is not exactly representable in f32, so the table would "
            f"round a block surface; CollisionBox needs to become [f64; 6]"
        )
    text = repr(float(value))
    return text if "." in text or "e" in text else f"{text}.0"


def reflow(text: str) -> str:
    """Re-wrap the module doc comment, which the substitutions above unwrap.

    The counts are what the prose is about -- "326 shapes for 32366 states" --
    so they are interpolated into sentences rather than tacked on, and a
    version whose numbers are a different width would otherwise leave the
    paragraph ragged. Only `//!` lines are touched; the item docs below carry
    no substitutions and are already wrapped as written.
    """
    lines = text.split("\n")
    out: list[str] = []
    paragraph: list[str] = []

    def flush() -> None:
        if not paragraph:
            return
        # A break inside an inline code span reads as two spans, so the
        # spaces inside backticks are hidden from the wrapper and restored
        # after it.
        joined = re.sub(
            r"`[^`]*`", lambda m: m.group(0).replace(" ", "\x00"), " ".join(paragraph)
        )
        wrapped = textwrap.wrap(
            joined, width=76, break_long_words=False, break_on_hyphens=False
        )
        out.extend(f"//! {line}".replace("\x00", " ") for line in wrapped)
        paragraph.clear()

    for line in lines:
        if not line.startswith("//!"):
            flush()
            out.append(line)
            continue
        body = line[3:].strip()
        # A blank line ends a paragraph and a heading is its own line; anything
        # else joins the paragraph being built.
        if not body:
            flush()
            out.append("//!")
        elif body.startswith("#"):
            flush()
            out.append(f"//! {body}")
        else:
            paragraph.append(body)
    flush()
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--shapes", type=Path, required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--protocol", required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    data = json.loads(args.shapes.read_text())
    shapes = data["shapes"]
    state_shapes = data["stateShapes"]

    if data["minecraftVersion"] != args.version:
        raise SystemExit(
            f"the shape dump is Minecraft {data['minecraftVersion']} but the "
            f"pin is {args.version}"
        )
    if len(state_shapes) != data["stateCount"]:
        raise SystemExit(
            f"{len(state_shapes)} state entries for a stateCount of "
            f"{data['stateCount']}"
        )
    # The indices below are `u16`. 65536 distinct shapes is far beyond the few
    # hundred the game has, but the failure would be a silently truncated index
    # pointing at the wrong shape, so it is checked rather than assumed.
    if len(shapes) > 0xFFFF:
        raise SystemExit(f"{len(shapes)} distinct shapes does not fit a u16 index")
    for index in state_shapes:
        if not 0 <= index < len(shapes):
            raise SystemExit(f"state shape index {index} is outside the shape table")

    # A shape's identity is its box list, so two equal lists mean the extractor
    # stopped deduplicating -- which costs nothing but says the dump is not
    # what this file claims it is.
    keys = {tuple(tuple(box) for box in shape) for shape in shapes}
    if len(keys) != len(shapes):
        raise SystemExit(
            f"{len(shapes)} shapes with only {len(keys)} distinct box lists; "
            f"the dump is not deduplicated"
        )

    # Stone and air. Both exist in every version, and counting the states that
    # share them is what makes the deduplication claim in the docs checkable.
    unit_cube = [[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]]
    if unit_cube not in shapes or [] not in shapes:
        raise SystemExit(
            "the shape table has no unit cube or no empty shape, which every "
            "version has"
        )

    distinct = {value for shape in shapes for box in shape for value in box}
    shape_table = "".join(
        "    &[{}],\n".format(
            ", ".join("[{}]".format(", ".join(number(v) for v in box)) for box in shape)
        )
        for shape in shapes
    )
    state_table = "".join(f"    {index},\n" for index in state_shapes)

    text = HEADER.format(version=args.version, protocol=args.protocol)
    text += reflow(PREAMBLE.format(
        version=args.version,
        states=len(state_shapes),
        shape_count=len(shapes),
        boxes=sum(len(shape) for shape in shapes),
        total_boxes=sum(len(shapes[index]) for index in state_shapes),
        full_cube=state_shapes.count(shapes.index(unit_cube)),
        empty=state_shapes.count(shapes.index([])),
        distinct=len(distinct),
        shape_table=shape_table,
        state_table=state_table,
    ))
    args.out.write_text(text)


if __name__ == "__main__":
    main()
