"""Turn the tag dump into a Rust module.

The dump is one blob of already-encoded id lists per registry plus an index
naming each tag and how many bytes it occupies. That shape survives into Rust
unchanged: the blob rides along as a file and `include_bytes!` puts it in
rodata, so writing an `update_tags` packet is a memcpy per tag rather than a
few thousand `VarInt`s built from a parsed tree on every join.
"""

import argparse
import json
import pathlib


HEADER = """// @generated by nix/generate-tag-data.py from Minecraft {version}.
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-tag-data

//! Every tag a client is told about during configuration.
//!
//! A client loads tags from its own data packs, but it keeps them only until
//! the server speaks: handling `update_tags` replaces the whole map. A server
//! that sends an empty one therefore leaves the client with no tags at all,
//! and the next registry element naming a tag fails to parse -- which fails
//! the whole registry load, which fails `finish_configuration` and
//! disconnects with "Network Protocol Error". Sending these bytes is not an
//! optimisation; it is what makes a join work.
//!
//! # All of them, not the ones something happens to reference
//!
//! This is the full map `TagNetworkSerialization.serializeTagsToNetwork`
//! produces, which is what vanilla sends:
//! {tags} tags across {registries} registries, {encoded_len} bytes of body.
//!
//! Trimming it to the tags today's registry elements name would be smaller,
//! and would break the first time a version bump or a data pack adds a
//! reference, with this module's own failure mode as the result.
//!
//! # Ids, not names
//!
//! A tag holds network ids, so these bytes are correct only for a server that
//! sends `registry_data` in the element order [`crate::registry_data`]
//! carries. Both come from one iteration of the server's own
//! `MappedRegistry`, which is by id.
//!
//! The one departure from the server's own bytes is that registries and tag
//! names are sorted. Vanilla builds both maps as a `HashMap`, so its order
//! changes from run to run; a map is unordered on the wire, so a client reads
//! the same tags either way.

use crate::{{Encode, Error, Result, Writer}};

/// Every registry with at least one tag, sorted by name.
///
/// `serializeTagsToNetwork` drops the empty payloads, so a registry absent
/// from here has no tags rather than unknown ones.
pub static ALL: &[&RegistryTagSet] = &[
{all_entries}];

/// Byte length of the `minecraft:update_tags` body [`VanillaTags`] writes.
///
/// Committed rather than computed so that a change in the dump shows up as a
/// diff here, and so a test can hold the encoder to it.
pub const ENCODED_LEN: usize = {encoded_len};

/// The tags of one registry (`TagNetworkSerialization.NetworkPayload`).
#[derive(Debug, Clone, Copy)]
pub struct RegistryTagSet {{
    /// Registry the ids index into, e.g. `minecraft:block`.
    pub registry: &'static str,
    /// Tag names without the `#`, sorted.
    pub names: &'static [&'static str],
    /// Byte length of each tag's encoded id list, parallel to
    /// [`names`](Self::names).
    pub lengths: &'static [u32],
    /// Each tag's `VarInt` element count followed by its `VarInt` ids,
    /// concatenated in the same order.
    pub payloads: &'static [u8],
}}

impl RegistryTagSet {{
    /// Number of tags.
    #[must_use]
    pub const fn len(&self) -> usize {{
        self.names.len()
    }}

    /// True when the registry has no tags, which none of these do.
    #[must_use]
    pub const fn is_empty(&self) -> bool {{
        self.names.is_empty()
    }}

    /// Walk the tags as `(name, encoded id list)`.
    pub fn iter(&self) -> impl Iterator<Item = (&'static str, &'static [u8])> + '_ {{
        let mut offset = 0usize;
        self.names.iter().zip(self.lengths).map(move |(name, length)| {{
            let length = *length as usize;
            let payload = &self.payloads[offset..offset + length];
            offset += length;
            (*name, payload)
        }})
    }}

    /// Look up one tag's encoded id list by name.
    #[must_use]
    pub fn get(&self, name: &str) -> Option<&'static [u8]> {{
        self.iter()
            .find_map(|(tag, payload)| (tag == name).then_some(payload))
    }}

    /// Write this registry's entry in an `update_tags` body.
    ///
    /// # Errors
    /// Returns [`Error::NegativeLength`] only for a tag count a `VarInt`
    /// cannot describe, which no vanilla registry approaches.
    pub fn encode(&self, writer: &mut Writer) -> Result<()> {{
        writer.string(self.registry)?;
        writer.var_int(i32::try_from(self.len()).map_err(|_| Error::NegativeLength(-1))?);
        for (name, payload) in self.iter() {{
            writer.string(name)?;
            // `FriendlyByteBuf.writeIntIdList` bytes, element count included.
            writer.raw(payload);
        }}
        Ok(())
    }}
}}

/// Find a registry's tags by name.
#[must_use]
pub fn by_name(name: &str) -> Option<&'static RegistryTagSet> {{
    ALL.iter().copied().find(|set| set.registry == name)
}}

/// The whole map, as the body of a `minecraft:update_tags` packet.
///
/// A type of its own rather than
/// [`crate::packets::configuration::UpdateTags`] because the ids are already
/// encoded in rodata: writing this is {tags} memcpys, where filling in the
/// packet struct would build {tags} `Vec`s on every join.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct VanillaTags;

impl Encode for VanillaTags {{
    fn encode(&self, writer: &mut Writer) -> Result<()> {{
        writer.var_int(i32::try_from(ALL.len()).map_err(|_| Error::NegativeLength(-1))?);
        for set in ALL {{
            set.encode(writer)?;
        }}
        Ok(())
    }}
}}
"""


def rust_name(registry: str) -> str:
    """`minecraft:worldgen/biome` -> `WORLDGEN_BIOME`."""
    without_namespace = registry.split(":", 1)[-1]
    return without_namespace.replace("/", "_").upper()


def var_int_len(value: int) -> int:
    """Bytes a non-negative `VarInt` occupies."""
    length = 1
    while value >= 0x80:
        value >>= 7
        length += 1
    return length


def string_len(text: str) -> int:
    """Bytes a length-prefixed UTF-8 string occupies on the wire."""
    encoded = len(text.encode())
    return var_int_len(encoded) + encoded


def body_len(index: list) -> int:
    """Byte length of the `update_tags` body the generated Rust writes."""
    total = var_int_len(len(index))
    for registry in index:
        total += string_len(registry["registry"]) + var_int_len(len(registry["tags"]))
        for tag in registry["tags"]:
            total += string_len(tag["name"]) + tag["length"]
    return total


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dump", required=True, type=pathlib.Path)
    parser.add_argument("--version", required=True)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    args = parser.parse_args()

    index = json.loads((args.dump / "index.json").read_text())

    args.out.mkdir(parents=True, exist_ok=True)

    body = []
    all_entries = []
    tags = 0
    for registry in index:
        name = registry["registry"]
        symbol = rust_name(name)
        blob = args.dump / registry["file"]
        (args.out / registry["file"]).write_bytes(blob.read_bytes())

        entries = registry["tags"]
        tags += len(entries)
        names = "".join(f'        "{tag["name"]}",\n' for tag in entries)
        lengths = "".join(f"        {tag['length']},\n" for tag in entries)
        total = sum(tag["length"] for tag in entries)
        elements = sum(tag["entries"] for tag in entries)
        all_entries.append(f"    &{symbol},\n")

        body.append(
            f"/// `{name}` ({len(entries)} tags over {elements} ids, "
            f"{total} bytes).\n"
            f"pub static {symbol}: RegistryTagSet = RegistryTagSet {{\n"
            f'    registry: "{name}",\n'
            f"    names: &[\n{names}    ],\n"
            f"    lengths: &[\n{lengths}    ],\n"
            f'    payloads: include_bytes!("{registry["file"]}"),\n'
            f"}};\n"
        )

    text = HEADER.format(
        version=args.version,
        all_entries="".join(all_entries),
        encoded_len=body_len(index),
        registries=len(index),
        tags=tags,
    )
    text += "\n" + "\n".join(body)
    (args.out / "mod.rs").write_text(text)


if __name__ == "__main__":
    main()
