// @generated by nix/generate-entity-types.py from Minecraft 26.2 (protocol 776).
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-entity-types

//! Entity type network ids for Minecraft 26.2.
//!
//! `minecraft:entity_type` is positional, so the number `add_entity` carries is an index
//! into it and moves whenever Mojang inserts a type. A pig is 90 on 1.20.1 and
//! 100 here. Nothing on the wire distinguishes the two, so a sender holding
//! the older numbering puts the wrong entity in the world rather than failing.
//!
//! The name is the part that survives a version bump, so a caller names the
//! type and this translates. Naming it through an associated constant rather
//! than through a string is what makes a rename a build failure:
//! [`EntityType::PIG`] stops existing, at the line that wanted a pig, rather
//! than [`entity_type`] quietly starting to return `None` at run time.

use crate::types::RegistryId;

/// One entry of `minecraft:entity_type`, and the id this version sends for it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct EntityType {
    name: &'static str,
    id: i32,
}

impl EntityType {
    /// Private so that the only values in existence are the table's own.
    const fn new(name: &'static str, id: i32) -> Self {
        Self { name, id }
    }

    /// Namespaced name, e.g. `minecraft:pig`.
    #[must_use]
    pub const fn name(self) -> &'static str {
        self.name
    }

    /// Network id, which is what `add_entity` carries.
    #[must_use]
    pub const fn id(self) -> RegistryId {
        RegistryId(self.id)
    }
}

/// How many entity types this version has, so every valid id is below this.
pub const ENTITY_TYPE_COUNT: usize = 158;

/// The entity type of that name, for a name only known at run time.
///
/// A name known at compile time should go through the constant of the same
/// name instead, so that a version bump dropping the type fails to build.
#[must_use]
pub fn entity_type(name: &str) -> Option<EntityType> {
    // A scan rather than a binary search: the table is small, and the caller
    // is translating a name off the wire rather than doing this per tick.
    // Keeping the array in id order instead lets the id double as the index.
    ENTITY_TYPES
        .iter()
        .copied()
        .find(|entry| entry.name == name)
}

/// Every entity type, in network-id order, so the index is the id.
pub static ENTITY_TYPES: &[EntityType] = &[
    EntityType::ACACIA_BOAT,
    EntityType::ACACIA_CHEST_BOAT,
    EntityType::ALLAY,
    EntityType::AREA_EFFECT_CLOUD,
    EntityType::ARMADILLO,
    EntityType::ARMOR_STAND,
    EntityType::ARROW,
    EntityType::AXOLOTL,
    EntityType::BAMBOO_CHEST_RAFT,
    EntityType::BAMBOO_RAFT,
    EntityType::BAT,
    EntityType::BEE,
    EntityType::BIRCH_BOAT,
    EntityType::BIRCH_CHEST_BOAT,
    EntityType::BLAZE,
    EntityType::BLOCK_DISPLAY,
    EntityType::BOGGED,
    EntityType::BREEZE,
    EntityType::BREEZE_WIND_CHARGE,
    EntityType::CAMEL,
    EntityType::CAMEL_HUSK,
    EntityType::CAT,
    EntityType::CAVE_SPIDER,
    EntityType::CHERRY_BOAT,
    EntityType::CHERRY_CHEST_BOAT,
    EntityType::CHEST_MINECART,
    EntityType::CHICKEN,
    EntityType::COD,
    EntityType::COPPER_GOLEM,
    EntityType::COMMAND_BLOCK_MINECART,
    EntityType::COW,
    EntityType::CREAKING,
    EntityType::CREEPER,
    EntityType::DARK_OAK_BOAT,
    EntityType::DARK_OAK_CHEST_BOAT,
    EntityType::DOLPHIN,
    EntityType::DONKEY,
    EntityType::DRAGON_FIREBALL,
    EntityType::DROWNED,
    EntityType::EGG,
    EntityType::ELDER_GUARDIAN,
    EntityType::ENDERMAN,
    EntityType::ENDERMITE,
    EntityType::ENDER_DRAGON,
    EntityType::ENDER_PEARL,
    EntityType::END_CRYSTAL,
    EntityType::EVOKER,
    EntityType::EVOKER_FANGS,
    EntityType::EXPERIENCE_BOTTLE,
    EntityType::EXPERIENCE_ORB,
    EntityType::EYE_OF_ENDER,
    EntityType::FALLING_BLOCK,
    EntityType::FIREBALL,
    EntityType::FIREWORK_ROCKET,
    EntityType::FOX,
    EntityType::FROG,
    EntityType::FURNACE_MINECART,
    EntityType::GHAST,
    EntityType::HAPPY_GHAST,
    EntityType::GIANT,
    EntityType::GLOW_ITEM_FRAME,
    EntityType::GLOW_SQUID,
    EntityType::GOAT,
    EntityType::GUARDIAN,
    EntityType::HOGLIN,
    EntityType::HOPPER_MINECART,
    EntityType::HORSE,
    EntityType::HUSK,
    EntityType::ILLUSIONER,
    EntityType::INTERACTION,
    EntityType::IRON_GOLEM,
    EntityType::ITEM,
    EntityType::ITEM_DISPLAY,
    EntityType::ITEM_FRAME,
    EntityType::JUNGLE_BOAT,
    EntityType::JUNGLE_CHEST_BOAT,
    EntityType::LEASH_KNOT,
    EntityType::LIGHTNING_BOLT,
    EntityType::LLAMA,
    EntityType::LLAMA_SPIT,
    EntityType::MAGMA_CUBE,
    EntityType::MANGROVE_BOAT,
    EntityType::MANGROVE_CHEST_BOAT,
    EntityType::MANNEQUIN,
    EntityType::MARKER,
    EntityType::MINECART,
    EntityType::MOOSHROOM,
    EntityType::MULE,
    EntityType::NAUTILUS,
    EntityType::OAK_BOAT,
    EntityType::OAK_CHEST_BOAT,
    EntityType::OCELOT,
    EntityType::OMINOUS_ITEM_SPAWNER,
    EntityType::PAINTING,
    EntityType::PALE_OAK_BOAT,
    EntityType::PALE_OAK_CHEST_BOAT,
    EntityType::PANDA,
    EntityType::PARCHED,
    EntityType::PARROT,
    EntityType::PHANTOM,
    EntityType::PIG,
    EntityType::PIGLIN,
    EntityType::PIGLIN_BRUTE,
    EntityType::PILLAGER,
    EntityType::POLAR_BEAR,
    EntityType::SPLASH_POTION,
    EntityType::LINGERING_POTION,
    EntityType::PUFFERFISH,
    EntityType::RABBIT,
    EntityType::RAVAGER,
    EntityType::SALMON,
    EntityType::SHEEP,
    EntityType::SHULKER,
    EntityType::SHULKER_BULLET,
    EntityType::SILVERFISH,
    EntityType::SKELETON,
    EntityType::SKELETON_HORSE,
    EntityType::SLIME,
    EntityType::SMALL_FIREBALL,
    EntityType::SNIFFER,
    EntityType::SNOWBALL,
    EntityType::SNOW_GOLEM,
    EntityType::SPAWNER_MINECART,
    EntityType::SPECTRAL_ARROW,
    EntityType::SPIDER,
    EntityType::SPRUCE_BOAT,
    EntityType::SPRUCE_CHEST_BOAT,
    EntityType::SQUID,
    EntityType::STRAY,
    EntityType::STRIDER,
    EntityType::SULFUR_CUBE,
    EntityType::TADPOLE,
    EntityType::TEXT_DISPLAY,
    EntityType::TNT,
    EntityType::TNT_MINECART,
    EntityType::TRADER_LLAMA,
    EntityType::TRIDENT,
    EntityType::TROPICAL_FISH,
    EntityType::TURTLE,
    EntityType::VEX,
    EntityType::VILLAGER,
    EntityType::VINDICATOR,
    EntityType::WANDERING_TRADER,
    EntityType::WARDEN,
    EntityType::WIND_CHARGE,
    EntityType::WITCH,
    EntityType::WITHER,
    EntityType::WITHER_SKELETON,
    EntityType::WITHER_SKULL,
    EntityType::WOLF,
    EntityType::ZOGLIN,
    EntityType::ZOMBIE,
    EntityType::ZOMBIE_HORSE,
    EntityType::ZOMBIE_NAUTILUS,
    EntityType::ZOMBIE_VILLAGER,
    EntityType::ZOMBIFIED_PIGLIN,
    EntityType::PLAYER,
    EntityType::FISHING_BOBBER,
];

// One constant per registry entry. Naming a type through one of these is what
// makes a version that renames or removes it fail to build.
impl EntityType {
    /// `minecraft:acacia_boat` (id 0).
    pub const ACACIA_BOAT: Self = Self::new("minecraft:acacia_boat", 0);
    /// `minecraft:acacia_chest_boat` (id 1).
    pub const ACACIA_CHEST_BOAT: Self = Self::new("minecraft:acacia_chest_boat", 1);
    /// `minecraft:allay` (id 2).
    pub const ALLAY: Self = Self::new("minecraft:allay", 2);
    /// `minecraft:area_effect_cloud` (id 3).
    pub const AREA_EFFECT_CLOUD: Self = Self::new("minecraft:area_effect_cloud", 3);
    /// `minecraft:armadillo` (id 4).
    pub const ARMADILLO: Self = Self::new("minecraft:armadillo", 4);
    /// `minecraft:armor_stand` (id 5).
    pub const ARMOR_STAND: Self = Self::new("minecraft:armor_stand", 5);
    /// `minecraft:arrow` (id 6).
    pub const ARROW: Self = Self::new("minecraft:arrow", 6);
    /// `minecraft:axolotl` (id 7).
    pub const AXOLOTL: Self = Self::new("minecraft:axolotl", 7);
    /// `minecraft:bamboo_chest_raft` (id 8).
    pub const BAMBOO_CHEST_RAFT: Self = Self::new("minecraft:bamboo_chest_raft", 8);
    /// `minecraft:bamboo_raft` (id 9).
    pub const BAMBOO_RAFT: Self = Self::new("minecraft:bamboo_raft", 9);
    /// `minecraft:bat` (id 10).
    pub const BAT: Self = Self::new("minecraft:bat", 10);
    /// `minecraft:bee` (id 11).
    pub const BEE: Self = Self::new("minecraft:bee", 11);
    /// `minecraft:birch_boat` (id 12).
    pub const BIRCH_BOAT: Self = Self::new("minecraft:birch_boat", 12);
    /// `minecraft:birch_chest_boat` (id 13).
    pub const BIRCH_CHEST_BOAT: Self = Self::new("minecraft:birch_chest_boat", 13);
    /// `minecraft:blaze` (id 14).
    pub const BLAZE: Self = Self::new("minecraft:blaze", 14);
    /// `minecraft:block_display` (id 15).
    pub const BLOCK_DISPLAY: Self = Self::new("minecraft:block_display", 15);
    /// `minecraft:bogged` (id 16).
    pub const BOGGED: Self = Self::new("minecraft:bogged", 16);
    /// `minecraft:breeze` (id 17).
    pub const BREEZE: Self = Self::new("minecraft:breeze", 17);
    /// `minecraft:breeze_wind_charge` (id 18).
    pub const BREEZE_WIND_CHARGE: Self = Self::new("minecraft:breeze_wind_charge", 18);
    /// `minecraft:camel` (id 19).
    pub const CAMEL: Self = Self::new("minecraft:camel", 19);
    /// `minecraft:camel_husk` (id 20).
    pub const CAMEL_HUSK: Self = Self::new("minecraft:camel_husk", 20);
    /// `minecraft:cat` (id 21).
    pub const CAT: Self = Self::new("minecraft:cat", 21);
    /// `minecraft:cave_spider` (id 22).
    pub const CAVE_SPIDER: Self = Self::new("minecraft:cave_spider", 22);
    /// `minecraft:cherry_boat` (id 23).
    pub const CHERRY_BOAT: Self = Self::new("minecraft:cherry_boat", 23);
    /// `minecraft:cherry_chest_boat` (id 24).
    pub const CHERRY_CHEST_BOAT: Self = Self::new("minecraft:cherry_chest_boat", 24);
    /// `minecraft:chest_minecart` (id 25).
    pub const CHEST_MINECART: Self = Self::new("minecraft:chest_minecart", 25);
    /// `minecraft:chicken` (id 26).
    pub const CHICKEN: Self = Self::new("minecraft:chicken", 26);
    /// `minecraft:cod` (id 27).
    pub const COD: Self = Self::new("minecraft:cod", 27);
    /// `minecraft:command_block_minecart` (id 29).
    pub const COMMAND_BLOCK_MINECART: Self = Self::new("minecraft:command_block_minecart", 29);
    /// `minecraft:copper_golem` (id 28).
    pub const COPPER_GOLEM: Self = Self::new("minecraft:copper_golem", 28);
    /// `minecraft:cow` (id 30).
    pub const COW: Self = Self::new("minecraft:cow", 30);
    /// `minecraft:creaking` (id 31).
    pub const CREAKING: Self = Self::new("minecraft:creaking", 31);
    /// `minecraft:creeper` (id 32).
    pub const CREEPER: Self = Self::new("minecraft:creeper", 32);
    /// `minecraft:dark_oak_boat` (id 33).
    pub const DARK_OAK_BOAT: Self = Self::new("minecraft:dark_oak_boat", 33);
    /// `minecraft:dark_oak_chest_boat` (id 34).
    pub const DARK_OAK_CHEST_BOAT: Self = Self::new("minecraft:dark_oak_chest_boat", 34);
    /// `minecraft:dolphin` (id 35).
    pub const DOLPHIN: Self = Self::new("minecraft:dolphin", 35);
    /// `minecraft:donkey` (id 36).
    pub const DONKEY: Self = Self::new("minecraft:donkey", 36);
    /// `minecraft:dragon_fireball` (id 37).
    pub const DRAGON_FIREBALL: Self = Self::new("minecraft:dragon_fireball", 37);
    /// `minecraft:drowned` (id 38).
    pub const DROWNED: Self = Self::new("minecraft:drowned", 38);
    /// `minecraft:egg` (id 39).
    pub const EGG: Self = Self::new("minecraft:egg", 39);
    /// `minecraft:elder_guardian` (id 40).
    pub const ELDER_GUARDIAN: Self = Self::new("minecraft:elder_guardian", 40);
    /// `minecraft:enderman` (id 41).
    pub const ENDERMAN: Self = Self::new("minecraft:enderman", 41);
    /// `minecraft:endermite` (id 42).
    pub const ENDERMITE: Self = Self::new("minecraft:endermite", 42);
    /// `minecraft:ender_dragon` (id 43).
    pub const ENDER_DRAGON: Self = Self::new("minecraft:ender_dragon", 43);
    /// `minecraft:ender_pearl` (id 44).
    pub const ENDER_PEARL: Self = Self::new("minecraft:ender_pearl", 44);
    /// `minecraft:end_crystal` (id 45).
    pub const END_CRYSTAL: Self = Self::new("minecraft:end_crystal", 45);
    /// `minecraft:evoker` (id 46).
    pub const EVOKER: Self = Self::new("minecraft:evoker", 46);
    /// `minecraft:evoker_fangs` (id 47).
    pub const EVOKER_FANGS: Self = Self::new("minecraft:evoker_fangs", 47);
    /// `minecraft:experience_bottle` (id 48).
    pub const EXPERIENCE_BOTTLE: Self = Self::new("minecraft:experience_bottle", 48);
    /// `minecraft:experience_orb` (id 49).
    pub const EXPERIENCE_ORB: Self = Self::new("minecraft:experience_orb", 49);
    /// `minecraft:eye_of_ender` (id 50).
    pub const EYE_OF_ENDER: Self = Self::new("minecraft:eye_of_ender", 50);
    /// `minecraft:falling_block` (id 51).
    pub const FALLING_BLOCK: Self = Self::new("minecraft:falling_block", 51);
    /// `minecraft:fireball` (id 52).
    pub const FIREBALL: Self = Self::new("minecraft:fireball", 52);
    /// `minecraft:firework_rocket` (id 53).
    pub const FIREWORK_ROCKET: Self = Self::new("minecraft:firework_rocket", 53);
    /// `minecraft:fishing_bobber` (id 157).
    pub const FISHING_BOBBER: Self = Self::new("minecraft:fishing_bobber", 157);
    /// `minecraft:fox` (id 54).
    pub const FOX: Self = Self::new("minecraft:fox", 54);
    /// `minecraft:frog` (id 55).
    pub const FROG: Self = Self::new("minecraft:frog", 55);
    /// `minecraft:furnace_minecart` (id 56).
    pub const FURNACE_MINECART: Self = Self::new("minecraft:furnace_minecart", 56);
    /// `minecraft:ghast` (id 57).
    pub const GHAST: Self = Self::new("minecraft:ghast", 57);
    /// `minecraft:giant` (id 59).
    pub const GIANT: Self = Self::new("minecraft:giant", 59);
    /// `minecraft:glow_item_frame` (id 60).
    pub const GLOW_ITEM_FRAME: Self = Self::new("minecraft:glow_item_frame", 60);
    /// `minecraft:glow_squid` (id 61).
    pub const GLOW_SQUID: Self = Self::new("minecraft:glow_squid", 61);
    /// `minecraft:goat` (id 62).
    pub const GOAT: Self = Self::new("minecraft:goat", 62);
    /// `minecraft:guardian` (id 63).
    pub const GUARDIAN: Self = Self::new("minecraft:guardian", 63);
    /// `minecraft:happy_ghast` (id 58).
    pub const HAPPY_GHAST: Self = Self::new("minecraft:happy_ghast", 58);
    /// `minecraft:hoglin` (id 64).
    pub const HOGLIN: Self = Self::new("minecraft:hoglin", 64);
    /// `minecraft:hopper_minecart` (id 65).
    pub const HOPPER_MINECART: Self = Self::new("minecraft:hopper_minecart", 65);
    /// `minecraft:horse` (id 66).
    pub const HORSE: Self = Self::new("minecraft:horse", 66);
    /// `minecraft:husk` (id 67).
    pub const HUSK: Self = Self::new("minecraft:husk", 67);
    /// `minecraft:illusioner` (id 68).
    pub const ILLUSIONER: Self = Self::new("minecraft:illusioner", 68);
    /// `minecraft:interaction` (id 69).
    pub const INTERACTION: Self = Self::new("minecraft:interaction", 69);
    /// `minecraft:iron_golem` (id 70).
    pub const IRON_GOLEM: Self = Self::new("minecraft:iron_golem", 70);
    /// `minecraft:item` (id 71).
    pub const ITEM: Self = Self::new("minecraft:item", 71);
    /// `minecraft:item_display` (id 72).
    pub const ITEM_DISPLAY: Self = Self::new("minecraft:item_display", 72);
    /// `minecraft:item_frame` (id 73).
    pub const ITEM_FRAME: Self = Self::new("minecraft:item_frame", 73);
    /// `minecraft:jungle_boat` (id 74).
    pub const JUNGLE_BOAT: Self = Self::new("minecraft:jungle_boat", 74);
    /// `minecraft:jungle_chest_boat` (id 75).
    pub const JUNGLE_CHEST_BOAT: Self = Self::new("minecraft:jungle_chest_boat", 75);
    /// `minecraft:leash_knot` (id 76).
    pub const LEASH_KNOT: Self = Self::new("minecraft:leash_knot", 76);
    /// `minecraft:lightning_bolt` (id 77).
    pub const LIGHTNING_BOLT: Self = Self::new("minecraft:lightning_bolt", 77);
    /// `minecraft:lingering_potion` (id 106).
    pub const LINGERING_POTION: Self = Self::new("minecraft:lingering_potion", 106);
    /// `minecraft:llama` (id 78).
    pub const LLAMA: Self = Self::new("minecraft:llama", 78);
    /// `minecraft:llama_spit` (id 79).
    pub const LLAMA_SPIT: Self = Self::new("minecraft:llama_spit", 79);
    /// `minecraft:magma_cube` (id 80).
    pub const MAGMA_CUBE: Self = Self::new("minecraft:magma_cube", 80);
    /// `minecraft:mangrove_boat` (id 81).
    pub const MANGROVE_BOAT: Self = Self::new("minecraft:mangrove_boat", 81);
    /// `minecraft:mangrove_chest_boat` (id 82).
    pub const MANGROVE_CHEST_BOAT: Self = Self::new("minecraft:mangrove_chest_boat", 82);
    /// `minecraft:mannequin` (id 83).
    pub const MANNEQUIN: Self = Self::new("minecraft:mannequin", 83);
    /// `minecraft:marker` (id 84).
    pub const MARKER: Self = Self::new("minecraft:marker", 84);
    /// `minecraft:minecart` (id 85).
    pub const MINECART: Self = Self::new("minecraft:minecart", 85);
    /// `minecraft:mooshroom` (id 86).
    pub const MOOSHROOM: Self = Self::new("minecraft:mooshroom", 86);
    /// `minecraft:mule` (id 87).
    pub const MULE: Self = Self::new("minecraft:mule", 87);
    /// `minecraft:nautilus` (id 88).
    pub const NAUTILUS: Self = Self::new("minecraft:nautilus", 88);
    /// `minecraft:oak_boat` (id 89).
    pub const OAK_BOAT: Self = Self::new("minecraft:oak_boat", 89);
    /// `minecraft:oak_chest_boat` (id 90).
    pub const OAK_CHEST_BOAT: Self = Self::new("minecraft:oak_chest_boat", 90);
    /// `minecraft:ocelot` (id 91).
    pub const OCELOT: Self = Self::new("minecraft:ocelot", 91);
    /// `minecraft:ominous_item_spawner` (id 92).
    pub const OMINOUS_ITEM_SPAWNER: Self = Self::new("minecraft:ominous_item_spawner", 92);
    /// `minecraft:painting` (id 93).
    pub const PAINTING: Self = Self::new("minecraft:painting", 93);
    /// `minecraft:pale_oak_boat` (id 94).
    pub const PALE_OAK_BOAT: Self = Self::new("minecraft:pale_oak_boat", 94);
    /// `minecraft:pale_oak_chest_boat` (id 95).
    pub const PALE_OAK_CHEST_BOAT: Self = Self::new("minecraft:pale_oak_chest_boat", 95);
    /// `minecraft:panda` (id 96).
    pub const PANDA: Self = Self::new("minecraft:panda", 96);
    /// `minecraft:parched` (id 97).
    pub const PARCHED: Self = Self::new("minecraft:parched", 97);
    /// `minecraft:parrot` (id 98).
    pub const PARROT: Self = Self::new("minecraft:parrot", 98);
    /// `minecraft:phantom` (id 99).
    pub const PHANTOM: Self = Self::new("minecraft:phantom", 99);
    /// `minecraft:pig` (id 100).
    pub const PIG: Self = Self::new("minecraft:pig", 100);
    /// `minecraft:piglin` (id 101).
    pub const PIGLIN: Self = Self::new("minecraft:piglin", 101);
    /// `minecraft:piglin_brute` (id 102).
    pub const PIGLIN_BRUTE: Self = Self::new("minecraft:piglin_brute", 102);
    /// `minecraft:pillager` (id 103).
    pub const PILLAGER: Self = Self::new("minecraft:pillager", 103);
    /// `minecraft:player` (id 156).
    pub const PLAYER: Self = Self::new("minecraft:player", 156);
    /// `minecraft:polar_bear` (id 104).
    pub const POLAR_BEAR: Self = Self::new("minecraft:polar_bear", 104);
    /// `minecraft:pufferfish` (id 107).
    pub const PUFFERFISH: Self = Self::new("minecraft:pufferfish", 107);
    /// `minecraft:rabbit` (id 108).
    pub const RABBIT: Self = Self::new("minecraft:rabbit", 108);
    /// `minecraft:ravager` (id 109).
    pub const RAVAGER: Self = Self::new("minecraft:ravager", 109);
    /// `minecraft:salmon` (id 110).
    pub const SALMON: Self = Self::new("minecraft:salmon", 110);
    /// `minecraft:sheep` (id 111).
    pub const SHEEP: Self = Self::new("minecraft:sheep", 111);
    /// `minecraft:shulker` (id 112).
    pub const SHULKER: Self = Self::new("minecraft:shulker", 112);
    /// `minecraft:shulker_bullet` (id 113).
    pub const SHULKER_BULLET: Self = Self::new("minecraft:shulker_bullet", 113);
    /// `minecraft:silverfish` (id 114).
    pub const SILVERFISH: Self = Self::new("minecraft:silverfish", 114);
    /// `minecraft:skeleton` (id 115).
    pub const SKELETON: Self = Self::new("minecraft:skeleton", 115);
    /// `minecraft:skeleton_horse` (id 116).
    pub const SKELETON_HORSE: Self = Self::new("minecraft:skeleton_horse", 116);
    /// `minecraft:slime` (id 117).
    pub const SLIME: Self = Self::new("minecraft:slime", 117);
    /// `minecraft:small_fireball` (id 118).
    pub const SMALL_FIREBALL: Self = Self::new("minecraft:small_fireball", 118);
    /// `minecraft:sniffer` (id 119).
    pub const SNIFFER: Self = Self::new("minecraft:sniffer", 119);
    /// `minecraft:snowball` (id 120).
    pub const SNOWBALL: Self = Self::new("minecraft:snowball", 120);
    /// `minecraft:snow_golem` (id 121).
    pub const SNOW_GOLEM: Self = Self::new("minecraft:snow_golem", 121);
    /// `minecraft:spawner_minecart` (id 122).
    pub const SPAWNER_MINECART: Self = Self::new("minecraft:spawner_minecart", 122);
    /// `minecraft:spectral_arrow` (id 123).
    pub const SPECTRAL_ARROW: Self = Self::new("minecraft:spectral_arrow", 123);
    /// `minecraft:spider` (id 124).
    pub const SPIDER: Self = Self::new("minecraft:spider", 124);
    /// `minecraft:splash_potion` (id 105).
    pub const SPLASH_POTION: Self = Self::new("minecraft:splash_potion", 105);
    /// `minecraft:spruce_boat` (id 125).
    pub const SPRUCE_BOAT: Self = Self::new("minecraft:spruce_boat", 125);
    /// `minecraft:spruce_chest_boat` (id 126).
    pub const SPRUCE_CHEST_BOAT: Self = Self::new("minecraft:spruce_chest_boat", 126);
    /// `minecraft:squid` (id 127).
    pub const SQUID: Self = Self::new("minecraft:squid", 127);
    /// `minecraft:stray` (id 128).
    pub const STRAY: Self = Self::new("minecraft:stray", 128);
    /// `minecraft:strider` (id 129).
    pub const STRIDER: Self = Self::new("minecraft:strider", 129);
    /// `minecraft:sulfur_cube` (id 130).
    pub const SULFUR_CUBE: Self = Self::new("minecraft:sulfur_cube", 130);
    /// `minecraft:tadpole` (id 131).
    pub const TADPOLE: Self = Self::new("minecraft:tadpole", 131);
    /// `minecraft:text_display` (id 132).
    pub const TEXT_DISPLAY: Self = Self::new("minecraft:text_display", 132);
    /// `minecraft:tnt` (id 133).
    pub const TNT: Self = Self::new("minecraft:tnt", 133);
    /// `minecraft:tnt_minecart` (id 134).
    pub const TNT_MINECART: Self = Self::new("minecraft:tnt_minecart", 134);
    /// `minecraft:trader_llama` (id 135).
    pub const TRADER_LLAMA: Self = Self::new("minecraft:trader_llama", 135);
    /// `minecraft:trident` (id 136).
    pub const TRIDENT: Self = Self::new("minecraft:trident", 136);
    /// `minecraft:tropical_fish` (id 137).
    pub const TROPICAL_FISH: Self = Self::new("minecraft:tropical_fish", 137);
    /// `minecraft:turtle` (id 138).
    pub const TURTLE: Self = Self::new("minecraft:turtle", 138);
    /// `minecraft:vex` (id 139).
    pub const VEX: Self = Self::new("minecraft:vex", 139);
    /// `minecraft:villager` (id 140).
    pub const VILLAGER: Self = Self::new("minecraft:villager", 140);
    /// `minecraft:vindicator` (id 141).
    pub const VINDICATOR: Self = Self::new("minecraft:vindicator", 141);
    /// `minecraft:wandering_trader` (id 142).
    pub const WANDERING_TRADER: Self = Self::new("minecraft:wandering_trader", 142);
    /// `minecraft:warden` (id 143).
    pub const WARDEN: Self = Self::new("minecraft:warden", 143);
    /// `minecraft:wind_charge` (id 144).
    pub const WIND_CHARGE: Self = Self::new("minecraft:wind_charge", 144);
    /// `minecraft:witch` (id 145).
    pub const WITCH: Self = Self::new("minecraft:witch", 145);
    /// `minecraft:wither` (id 146).
    pub const WITHER: Self = Self::new("minecraft:wither", 146);
    /// `minecraft:wither_skeleton` (id 147).
    pub const WITHER_SKELETON: Self = Self::new("minecraft:wither_skeleton", 147);
    /// `minecraft:wither_skull` (id 148).
    pub const WITHER_SKULL: Self = Self::new("minecraft:wither_skull", 148);
    /// `minecraft:wolf` (id 149).
    pub const WOLF: Self = Self::new("minecraft:wolf", 149);
    /// `minecraft:zoglin` (id 150).
    pub const ZOGLIN: Self = Self::new("minecraft:zoglin", 150);
    /// `minecraft:zombie` (id 151).
    pub const ZOMBIE: Self = Self::new("minecraft:zombie", 151);
    /// `minecraft:zombie_horse` (id 152).
    pub const ZOMBIE_HORSE: Self = Self::new("minecraft:zombie_horse", 152);
    /// `minecraft:zombie_nautilus` (id 153).
    pub const ZOMBIE_NAUTILUS: Self = Self::new("minecraft:zombie_nautilus", 153);
    /// `minecraft:zombie_villager` (id 154).
    pub const ZOMBIE_VILLAGER: Self = Self::new("minecraft:zombie_villager", 154);
    /// `minecraft:zombified_piglin` (id 155).
    pub const ZOMBIFIED_PIGLIN: Self = Self::new("minecraft:zombified_piglin", 155);
}
