// @generated by nix/generate-registry-data.py from Minecraft 26.2.
// Do not edit by hand. Regenerate with: nix run .#sync-minecraft-registry-data

//! Contents of the registries a server has to send during configuration.
//!
//! [`crate::generated::registry`] carries the *names* in every vanilla
//! registry, which is all `reports/registries.json` knows. The registries in
//! this module are datapack-loaded, so their contents exist only once the game
//! has built them; these bytes come from running
//! `RegistrySynchronization.packRegistry` against the pinned server jar.
//!
//! Each element is stored exactly as `ByteBufCodecs.TAG` writes it -- a type
//! byte then the payload, with no root name -- so
//! [`RegistryContents::encode`] copies rather than re-encodes. A caller that
//! wants to inspect or edit an element can still decode one with
//! [`crate::nbt::Tag`].
//!
//! # What a client needs
//!
//! [`DIMENSION_TYPE`], [`WORLDGEN_BIOME`] and [`CHAT_TYPE`] are the three a
//! client cannot start without: `login` indexes into the first, chunk sections
//! into the second and every chat message into the third. The rest are sent
//! because a vanilla client validates that it received the full set.

use crate::{Error, Result, Writer};

/// Every registry a server sends during configuration, in the order
/// `RegistryDataLoader.SYNCHRONIZED_REGISTRIES` lists them.
pub static ALL: &[&RegistryContents] = &[
    &WORLDGEN_BIOME,
    &CHAT_TYPE,
    &TRIM_PATTERN,
    &TRIM_MATERIAL,
    &WOLF_VARIANT,
    &WOLF_SOUND_VARIANT,
    &PIG_VARIANT,
    &PIG_SOUND_VARIANT,
    &FROG_VARIANT,
    &CAT_VARIANT,
    &CAT_SOUND_VARIANT,
    &COW_SOUND_VARIANT,
    &COW_VARIANT,
    &CHICKEN_SOUND_VARIANT,
    &CHICKEN_VARIANT,
    &ZOMBIE_NAUTILUS_VARIANT,
    &PAINTING_VARIANT,
    &SULFUR_CUBE_ARCHETYPE,
    &DIMENSION_TYPE,
    &DAMAGE_TYPE,
    &BANNER_PATTERN,
    &ENCHANTMENT,
    &JUKEBOX_SONG,
    &INSTRUMENT,
    &TEST_ENVIRONMENT,
    &TEST_INSTANCE,
    &DIALOG,
    &WORLD_CLOCK,
    &TIMELINE,
];

/// One synchronised registry and the contents of each of its elements.
#[derive(Debug, Clone, Copy)]
pub struct RegistryContents {
    /// Registry name, e.g. `minecraft:dimension_type`.
    pub registry: &'static str,
    /// Element names in network-id order; the index is the id.
    pub ids: &'static [&'static str],
    /// Byte length of each element's NBT, parallel to [`ids`](Self::ids).
    pub lengths: &'static [u32],
    /// Every element's NBT, concatenated in the same order.
    pub payloads: &'static [u8],
}

impl RegistryContents {
    /// Number of elements.
    #[must_use]
    pub const fn len(&self) -> usize {
        self.ids.len()
    }

    /// True when the registry has no elements, which none of these do.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.ids.is_empty()
    }

    /// Walk the elements as `(name, network NBT)`.
    pub fn iter(&self) -> impl Iterator<Item = (&'static str, &'static [u8])> + '_ {
        let mut offset = 0usize;
        self.ids.iter().zip(self.lengths).map(move |(id, length)| {
            let length = *length as usize;
            let payload = &self.payloads[offset..offset + length];
            offset += length;
            (*id, payload)
        })
    }

    /// Look up one element's NBT by name.
    #[must_use]
    pub fn get(&self, name: &str) -> Option<&'static [u8]> {
        self.iter()
            .find_map(|(id, payload)| (id == name).then_some(payload))
    }

    /// Write the body of a `minecraft:registry_data` packet.
    ///
    /// Every element is written with its contents, which is the case where the
    /// client reported no known packs. A server that honoured
    /// `select_known_packs` would write a `false` in place of the payload for
    /// the elements the client already has; see
    /// [`crate::packets::configuration`].
    ///
    /// # Errors
    /// Returns [`Error::NegativeLength`] only for an element count a `VarInt`
    /// cannot describe, which no vanilla registry approaches.
    pub fn encode(&self, writer: &mut Writer) -> Result<()> {
        writer.string(self.registry)?;
        writer.var_int(i32::try_from(self.len()).map_err(|_| Error::NegativeLength(-1))?);
        for (id, payload) in self.iter() {
            writer.string(id)?;
            // `ByteBufCodecs.TAG.apply(ByteBufCodecs::optional)`: present, then
            // the tag bytes verbatim.
            writer.bool(true);
            writer.raw(payload);
        }
        Ok(())
    }
}

/// Find a registry by name.
#[must_use]
pub fn by_name(name: &str) -> Option<&'static RegistryContents> {
    ALL.iter()
        .copied()
        .find(|registry| registry.registry == name)
}

/// `minecraft:worldgen/biome` (66 elements, 18627 bytes of NBT).
pub static WORLDGEN_BIOME: RegistryContents = RegistryContents {
    registry: "minecraft:worldgen/biome",
    ids: &[
        "minecraft:warm_ocean",
        "minecraft:deep_dark",
        "minecraft:eroded_badlands",
        "minecraft:dark_forest",
        "minecraft:sparse_jungle",
        "minecraft:small_end_islands",
        "minecraft:flower_forest",
        "minecraft:pale_garden",
        "minecraft:ocean",
        "minecraft:snowy_slopes",
        "minecraft:dripstone_caves",
        "minecraft:cold_ocean",
        "minecraft:basalt_deltas",
        "minecraft:meadow",
        "minecraft:taiga",
        "minecraft:snowy_beach",
        "minecraft:birch_forest",
        "minecraft:stony_shore",
        "minecraft:end_highlands",
        "minecraft:deep_lukewarm_ocean",
        "minecraft:windswept_forest",
        "minecraft:mangrove_swamp",
        "minecraft:snowy_taiga",
        "minecraft:frozen_river",
        "minecraft:the_end",
        "minecraft:lukewarm_ocean",
        "minecraft:crimson_forest",
        "minecraft:nether_wastes",
        "minecraft:old_growth_pine_taiga",
        "minecraft:windswept_hills",
        "minecraft:badlands",
        "minecraft:cherry_grove",
        "minecraft:jungle",
        "minecraft:savanna",
        "minecraft:ice_spikes",
        "minecraft:swamp",
        "minecraft:frozen_ocean",
        "minecraft:savanna_plateau",
        "minecraft:windswept_savanna",
        "minecraft:mushroom_fields",
        "minecraft:soul_sand_valley",
        "minecraft:plains",
        "minecraft:windswept_gravelly_hills",
        "minecraft:wooded_badlands",
        "minecraft:sunflower_plains",
        "minecraft:the_void",
        "minecraft:end_barrens",
        "minecraft:river",
        "minecraft:sulfur_caves",
        "minecraft:jagged_peaks",
        "minecraft:old_growth_birch_forest",
        "minecraft:end_midlands",
        "minecraft:desert",
        "minecraft:bamboo_jungle",
        "minecraft:snowy_plains",
        "minecraft:warped_forest",
        "minecraft:beach",
        "minecraft:frozen_peaks",
        "minecraft:grove",
        "minecraft:lush_caves",
        "minecraft:deep_ocean",
        "minecraft:deep_cold_ocean",
        "minecraft:stony_peaks",
        "minecraft:old_growth_spruce_taiga",
        "minecraft:forest",
        "minecraft:deep_frozen_ocean",
    ],
    lengths: &[
        456, 266, 313, 328, 270, 90, 270, 372, 412, 269, 272, 412, 647, 263, 142, 142, 263, 142,
        90, 456, 142, 507, 142, 412, 90, 456, 655, 546, 273, 142, 313, 361, 263, 142, 142, 469,
        173, 142, 142, 142, 653, 142, 142, 313, 142, 142, 90, 412, 374, 269, 263, 90, 263, 270,
        142, 650, 142, 269, 262, 267, 412, 412, 268, 273, 263, 173,
    ],
    payloads: include_bytes!("minecraft.worldgen.biome.nbt"),
};

/// `minecraft:chat_type` (7 elements, 1315 bytes of NBT).
pub static CHAT_TYPE: RegistryContents = RegistryContents {
    registry: "minecraft:chat_type",
    ids: &[
        "minecraft:team_msg_command_outgoing",
        "minecraft:say_command",
        "minecraft:team_msg_command_incoming",
        "minecraft:msg_command_outgoing",
        "minecraft:emote_command",
        "minecraft:chat",
        "minecraft:msg_command_incoming",
    ],
    lengths: &[182, 177, 182, 221, 163, 169, 221],
    payloads: include_bytes!("minecraft.chat_type.nbt"),
};

/// `minecraft:trim_pattern` (18 elements, 1720 bytes of NBT).
pub static TRIM_PATTERN: RegistryContents = RegistryContents {
    registry: "minecraft:trim_pattern",
    ids: &[
        "minecraft:wild",
        "minecraft:silence",
        "minecraft:spire",
        "minecraft:wayfinder",
        "minecraft:tide",
        "minecraft:ward",
        "minecraft:vex",
        "minecraft:rib",
        "minecraft:host",
        "minecraft:eye",
        "minecraft:bolt",
        "minecraft:coast",
        "minecraft:snout",
        "minecraft:sentry",
        "minecraft:raiser",
        "minecraft:dune",
        "minecraft:flow",
        "minecraft:shaper",
    ],
    lengths: &[
        94, 100, 96, 104, 94, 94, 92, 92, 94, 92, 94, 96, 96, 98, 98, 94, 94, 98,
    ],
    payloads: include_bytes!("minecraft.trim_pattern.nbt"),
};

/// `minecraft:trim_material` (11 elements, 1390 bytes of NBT).
pub static TRIM_MATERIAL: RegistryContents = RegistryContents {
    registry: "minecraft:trim_material",
    ids: &[
        "minecraft:resin",
        "minecraft:gold",
        "minecraft:iron",
        "minecraft:netherite",
        "minecraft:emerald",
        "minecraft:lapis",
        "minecraft:copper",
        "minecraft:quartz",
        "minecraft:amethyst",
        "minecraft:redstone",
        "minecraft:diamond",
    ],
    lengths: &[97, 150, 150, 170, 101, 97, 158, 99, 103, 103, 162],
    payloads: include_bytes!("minecraft.trim_material.nbt"),
};

/// `minecraft:wolf_variant` (9 elements, 2814 bytes of NBT).
pub static WOLF_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:wolf_variant",
    ids: &[
        "minecraft:snowy",
        "minecraft:striped",
        "minecraft:pale",
        "minecraft:chestnut",
        "minecraft:woods",
        "minecraft:rusty",
        "minecraft:spotted",
        "minecraft:ashen",
        "minecraft:black",
    ],
    lengths: &[312, 324, 276, 330, 312, 312, 324, 312, 312],
    payloads: include_bytes!("minecraft.wolf_variant.nbt"),
};

/// `minecraft:wolf_sound_variant` (7 elements, 4860 bytes of NBT).
pub static WOLF_SOUND_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:wolf_sound_variant",
    ids: &[
        "minecraft:puglin",
        "minecraft:big",
        "minecraft:classic",
        "minecraft:angry",
        "minecraft:sad",
        "minecraft:cute",
        "minecraft:grumpy",
    ],
    lengths: &[708, 690, 666, 702, 690, 696, 708],
    payloads: include_bytes!("minecraft.wolf_sound_variant.nbt"),
};

/// `minecraft:pig_variant` (3 elements, 312 bytes of NBT).
pub static PIG_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:pig_variant",
    ids: &["minecraft:cold", "minecraft:warm", "minecraft:temperate"],
    lengths: &[110, 96, 106],
    payloads: include_bytes!("minecraft.pig_variant.nbt"),
};

/// `minecraft:pig_sound_variant` (3 elements, 1446 bytes of NBT).
pub static PIG_SOUND_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:pig_sound_variant",
    ids: &["minecraft:classic", "minecraft:big", "minecraft:mini"],
    lengths: &[470, 486, 490],
    payloads: include_bytes!("minecraft.pig_sound_variant.nbt"),
};

/// `minecraft:frog_variant` (3 elements, 143 bytes of NBT).
pub static FROG_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:frog_variant",
    ids: &["minecraft:temperate", "minecraft:warm", "minecraft:cold"],
    lengths: &[51, 46, 46],
    payloads: include_bytes!("minecraft.frog_variant.nbt"),
};

/// `minecraft:cat_variant` (11 elements, 1122 bytes of NBT).
pub static CAT_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:cat_variant",
    ids: &[
        "minecraft:red",
        "minecraft:british_shorthair",
        "minecraft:white",
        "minecraft:jellie",
        "minecraft:ragdoll",
        "minecraft:siamese",
        "minecraft:tabby",
        "minecraft:black",
        "minecraft:all_black",
        "minecraft:persian",
        "minecraft:calico",
    ],
    lengths: &[94, 122, 98, 100, 102, 102, 98, 98, 106, 102, 100],
    payloads: include_bytes!("minecraft.cat_variant.nbt"),
};

/// `minecraft:cat_sound_variant` (2 elements, 1834 bytes of NBT).
pub static CAT_SOUND_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:cat_sound_variant",
    ids: &["minecraft:royal", "minecraft:classic"],
    lengths: &[944, 890],
    payloads: include_bytes!("minecraft.cat_sound_variant.nbt"),
};

/// `minecraft:cow_sound_variant` (2 elements, 364 bytes of NBT).
pub static COW_SOUND_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:cow_sound_variant",
    ids: &["minecraft:classic", "minecraft:moody"],
    lengths: &[170, 194],
    payloads: include_bytes!("minecraft.cow_sound_variant.nbt"),
};

/// `minecraft:cow_variant` (3 elements, 326 bytes of NBT).
pub static COW_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:cow_variant",
    ids: &["minecraft:temperate", "minecraft:warm", "minecraft:cold"],
    lengths: &[106, 110, 110],
    payloads: include_bytes!("minecraft.cow_variant.nbt"),
};

/// `minecraft:chicken_sound_variant` (2 elements, 860 bytes of NBT).
pub static CHICKEN_SOUND_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:chicken_sound_variant",
    ids: &["minecraft:classic", "minecraft:picky"],
    lengths: &[421, 439],
    payloads: include_bytes!("minecraft.chicken_sound_variant.nbt"),
};

/// `minecraft:chicken_variant` (3 elements, 360 bytes of NBT).
pub static CHICKEN_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:chicken_variant",
    ids: &["minecraft:cold", "minecraft:warm", "minecraft:temperate"],
    lengths: &[126, 112, 122],
    payloads: include_bytes!("minecraft.chicken_variant.nbt"),
};

/// `minecraft:zombie_nautilus_variant` (2 elements, 132 bytes of NBT).
pub static ZOMBIE_NAUTILUS_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:zombie_nautilus_variant",
    ids: &["minecraft:warm", "minecraft:temperate"],
    lengths: &[76, 56],
    payloads: include_bytes!("minecraft.zombie_nautilus_variant.nbt"),
};

/// `minecraft:painting_variant` (51 elements, 9751 bytes of NBT).
pub static PAINTING_VARIANT: RegistryContents = RegistryContents {
    registry: "minecraft:painting_variant",
    ids: &[
        "minecraft:skull_and_roses",
        "minecraft:sunflowers",
        "minecraft:match",
        "minecraft:passage",
        "minecraft:pool",
        "minecraft:sea",
        "minecraft:prairie_ride",
        "minecraft:donkey_kong",
        "minecraft:alban",
        "minecraft:finding",
        "minecraft:wanderer",
        "minecraft:pigscene",
        "minecraft:humble",
        "minecraft:aztec",
        "minecraft:burning_skull",
        "minecraft:orb",
        "minecraft:endboss",
        "minecraft:fire",
        "minecraft:owlemons",
        "minecraft:bomb",
        "minecraft:stage",
        "minecraft:plant",
        "minecraft:meditative",
        "minecraft:fern",
        "minecraft:bust",
        "minecraft:dennis",
        "minecraft:kebab",
        "minecraft:skeleton",
        "minecraft:wind",
        "minecraft:courbet",
        "minecraft:sunset",
        "minecraft:cavebird",
        "minecraft:void",
        "minecraft:pointer",
        "minecraft:wither",
        "minecraft:lowmist",
        "minecraft:baroque",
        "minecraft:cotan",
        "minecraft:earth",
        "minecraft:tides",
        "minecraft:pond",
        "minecraft:backyard",
        "minecraft:fighters",
        "minecraft:changing",
        "minecraft:bouquet",
        "minecraft:aztec2",
        "minecraft:water",
        "minecraft:creebet",
        "minecraft:wasteland",
        "minecraft:unpacked",
        "minecraft:graham",
    ],
    lengths: &[
        223, 208, 193, 199, 190, 187, 214, 211, 193, 199, 202, 202, 196, 193, 217, 187, 199, 122,
        202, 190, 193, 193, 208, 190, 190, 196, 193, 202, 122, 199, 196, 202, 190, 199, 126, 199,
        199, 193, 124, 193, 190, 202, 202, 202, 199, 196, 124, 199, 205, 202, 196,
    ],
    payloads: include_bytes!("minecraft.painting_variant.nbt"),
};

/// `minecraft:sulfur_cube_archetype` (12 elements, 12541 bytes of NBT).
pub static SULFUR_CUBE_ARCHETYPE: RegistryContents = RegistryContents {
    registry: "minecraft:sulfur_cube_archetype",
    ids: &[
        "minecraft:hot",
        "minecraft:sticky",
        "minecraft:fast_sliding",
        "minecraft:light",
        "minecraft:slow_bouncy",
        "minecraft:slow_sliding",
        "minecraft:bouncy",
        "minecraft:explosive",
        "minecraft:fast_flat",
        "minecraft:slow_flat",
        "minecraft:high_resistance",
        "minecraft:regular",
    ],
    lengths: &[
        1089, 1007, 1055, 1010, 1047, 1055, 1018, 1093, 1031, 1031, 1079, 1026,
    ],
    payloads: include_bytes!("minecraft.sulfur_cube_archetype.nbt"),
};

/// `minecraft:dimension_type` (4 elements, 3557 bytes of NBT).
pub static DIMENSION_TYPE: RegistryContents = RegistryContents {
    registry: "minecraft:dimension_type",
    ids: &[
        "minecraft:overworld",
        "minecraft:the_nether",
        "minecraft:the_end",
        "minecraft:overworld_caves",
    ],
    lengths: &[942, 824, 849, 942],
    payloads: include_bytes!("minecraft.dimension_type.nbt"),
};

/// `minecraft:damage_type` (51 elements, 4622 bytes of NBT).
pub static DAMAGE_TYPE: RegistryContents = RegistryContents {
    registry: "minecraft:damage_type",
    ids: &[
        "minecraft:fly_into_wall",
        "minecraft:sonic_boom",
        "minecraft:spit",
        "minecraft:lightning_bolt",
        "minecraft:thorns",
        "minecraft:mace_smash",
        "minecraft:in_wall",
        "minecraft:unattributed_fireball",
        "minecraft:thrown",
        "minecraft:lava",
        "minecraft:sting",
        "minecraft:player_attack",
        "minecraft:falling_stalactite",
        "minecraft:explosion",
        "minecraft:out_of_world",
        "minecraft:player_explosion",
        "minecraft:wind_charge",
        "minecraft:indirect_magic",
        "minecraft:campfire",
        "minecraft:sulfur_cube_hot",
        "minecraft:cactus",
        "minecraft:fireworks",
        "minecraft:dragon_breath",
        "minecraft:wither_skull",
        "minecraft:starve",
        "minecraft:falling_anvil",
        "minecraft:spear",
        "minecraft:arrow",
        "minecraft:hot_floor",
        "minecraft:on_fire",
        "minecraft:cramming",
        "minecraft:wither",
        "minecraft:bad_respawn_point",
        "minecraft:outside_border",
        "minecraft:falling_block",
        "minecraft:generic_kill",
        "minecraft:freeze",
        "minecraft:sweet_berry_bush",
        "minecraft:magic",
        "minecraft:mob_projectile",
        "minecraft:dry_out",
        "minecraft:ender_pearl",
        "minecraft:mob_attack_no_aggro",
        "minecraft:stalagmite",
        "minecraft:mob_attack",
        "minecraft:generic",
        "minecraft:fall",
        "minecraft:fireball",
        "minecraft:trident",
        "minecraft:drown",
        "minecraft:in_fire",
    ],
    lengths: &[
        89, 62, 81, 91, 102, 88, 84, 103, 84, 101, 83, 84, 95, 61, 88, 68, 81, 91, 103, 110, 84,
        87, 90, 89, 84, 83, 83, 83, 105, 103, 86, 84, 113, 91, 90, 89, 104, 110, 83, 81, 84, 118,
        81, 88, 81, 85, 118, 105, 85, 103, 103,
    ],
    payloads: include_bytes!("minecraft.damage_type.nbt"),
};

/// `minecraft:banner_pattern` (43 elements, 3910 bytes of NBT).
pub static BANNER_PATTERN: RegistryContents = RegistryContents {
    registry: "minecraft:banner_pattern",
    ids: &[
        "minecraft:diagonal_up_right",
        "minecraft:diagonal_up_left",
        "minecraft:flower",
        "minecraft:base",
        "minecraft:triangle_top",
        "minecraft:half_vertical",
        "minecraft:straight_cross",
        "minecraft:stripe_middle",
        "minecraft:gradient_up",
        "minecraft:guster",
        "minecraft:square_top_right",
        "minecraft:globe",
        "minecraft:curly_border",
        "minecraft:triangle_bottom",
        "minecraft:creeper",
        "minecraft:half_horizontal_bottom",
        "minecraft:diagonal_left",
        "minecraft:rhombus",
        "minecraft:gradient",
        "minecraft:half_horizontal",
        "minecraft:small_stripes",
        "minecraft:triangles_top",
        "minecraft:skull",
        "minecraft:border",
        "minecraft:bricks",
        "minecraft:stripe_downleft",
        "minecraft:stripe_downright",
        "minecraft:square_bottom_left",
        "minecraft:piglin",
        "minecraft:stripe_right",
        "minecraft:half_vertical_right",
        "minecraft:stripe_top",
        "minecraft:stripe_bottom",
        "minecraft:mojang",
        "minecraft:stripe_center",
        "minecraft:circle",
        "minecraft:square_top_left",
        "minecraft:square_bottom_right",
        "minecraft:flow",
        "minecraft:triangles_bottom",
        "minecraft:cross",
        "minecraft:diagonal_right",
        "minecraft:stripe_left",
    ],
    lengths: &[
        102, 100, 80, 76, 92, 94, 96, 94, 90, 80, 100, 78, 92, 98, 82, 112, 94, 82, 84, 98, 94, 94,
        78, 80, 80, 98, 100, 104, 80, 92, 106, 88, 94, 80, 94, 80, 98, 106, 76, 100, 78, 96, 90,
    ],
    payloads: include_bytes!("minecraft.banner_pattern.nbt"),
};

/// `minecraft:enchantment` (43 elements, 31117 bytes of NBT).
pub static ENCHANTMENT: RegistryContents = RegistryContents {
    registry: "minecraft:enchantment",
    ids: &[
        "minecraft:wind_burst",
        "minecraft:aqua_affinity",
        "minecraft:depth_strider",
        "minecraft:loyalty",
        "minecraft:soul_speed",
        "minecraft:lure",
        "minecraft:vanishing_curse",
        "minecraft:piercing",
        "minecraft:sweeping_edge",
        "minecraft:blast_protection",
        "minecraft:silk_touch",
        "minecraft:multishot",
        "minecraft:lunge",
        "minecraft:mending",
        "minecraft:density",
        "minecraft:swift_sneak",
        "minecraft:breach",
        "minecraft:impaling",
        "minecraft:luck_of_the_sea",
        "minecraft:unbreaking",
        "minecraft:protection",
        "minecraft:feather_falling",
        "minecraft:bane_of_arthropods",
        "minecraft:power",
        "minecraft:binding_curse",
        "minecraft:respiration",
        "minecraft:fire_aspect",
        "minecraft:thorns",
        "minecraft:knockback",
        "minecraft:efficiency",
        "minecraft:infinity",
        "minecraft:looting",
        "minecraft:frost_walker",
        "minecraft:punch",
        "minecraft:riptide",
        "minecraft:channeling",
        "minecraft:fortune",
        "minecraft:smite",
        "minecraft:sharpness",
        "minecraft:projectile_protection",
        "minecraft:fire_protection",
        "minecraft:quick_charge",
        "minecraft:flame",
    ],
    lengths: &[
        992, 522, 562, 443, 3320, 435, 333, 488, 631, 895, 427, 627, 1741, 373, 491, 498, 480, 615,
        442, 1040, 622, 621, 1245, 555, 332, 497, 625, 780, 432, 481, 494, 589, 1572, 558, 608,
        1498, 334, 661, 531, 676, 924, 754, 373,
    ],
    payloads: include_bytes!("minecraft.enchantment.nbt"),
};

/// `minecraft:jukebox_song` (22 elements, 3312 bytes of NBT).
pub static JUKEBOX_SONG: RegistryContents = RegistryContents {
    registry: "minecraft:jukebox_song",
    ids: &[
        "minecraft:precipice",
        "minecraft:lava_chicken",
        "minecraft:ward",
        "minecraft:stal",
        "minecraft:mall",
        "minecraft:relic",
        "minecraft:blocks",
        "minecraft:otherside",
        "minecraft:5",
        "minecraft:wait",
        "minecraft:bounce",
        "minecraft:13",
        "minecraft:far",
        "minecraft:strad",
        "minecraft:mellohi",
        "minecraft:pigstep",
        "minecraft:creator",
        "minecraft:11",
        "minecraft:chirp",
        "minecraft:tears",
        "minecraft:creator_music_box",
        "minecraft:cat",
    ],
    lengths: &[
        157, 163, 147, 147, 147, 149, 151, 157, 141, 147, 151, 143, 145, 149, 153, 153, 153, 143,
        149, 149, 173, 145,
    ],
    payloads: include_bytes!("minecraft.jukebox_song.nbt"),
};

/// `minecraft:instrument` (8 elements, 1166 bytes of NBT).
pub static INSTRUMENT: RegistryContents = RegistryContents {
    registry: "minecraft:instrument",
    ids: &[
        "minecraft:admire_goat_horn",
        "minecraft:sing_goat_horn",
        "minecraft:dream_goat_horn",
        "minecraft:call_goat_horn",
        "minecraft:yearn_goat_horn",
        "minecraft:feel_goat_horn",
        "minecraft:seek_goat_horn",
        "minecraft:ponder_goat_horn",
    ],
    lengths: &[147, 145, 146, 145, 146, 145, 145, 147],
    payloads: include_bytes!("minecraft.instrument.nbt"),
};

/// `minecraft:test_environment` (1 elements, 46 bytes of NBT).
pub static TEST_ENVIRONMENT: RegistryContents = RegistryContents {
    registry: "minecraft:test_environment",
    ids: &["minecraft:default"],
    lengths: &[46],
    payloads: include_bytes!("minecraft.test_environment.nbt"),
};

/// `minecraft:test_instance` (1 elements, 171 bytes of NBT).
pub static TEST_INSTANCE: RegistryContents = RegistryContents {
    registry: "minecraft:test_instance",
    ids: &["minecraft:always_pass"],
    lengths: &[171],
    payloads: include_bytes!("minecraft.test_instance.nbt"),
};

/// `minecraft:dialog` (3 elements, 742 bytes of NBT).
pub static DIALOG: RegistryContents = RegistryContents {
    registry: "minecraft:dialog",
    ids: &[
        "minecraft:custom_options",
        "minecraft:quick_actions",
        "minecraft:server_links",
    ],
    lengths: &[267, 256, 219],
    payloads: include_bytes!("minecraft.dialog.nbt"),
};

/// `minecraft:world_clock` (2 elements, 4 bytes of NBT).
pub static WORLD_CLOCK: RegistryContents = RegistryContents {
    registry: "minecraft:world_clock",
    ids: &["minecraft:the_end", "minecraft:overworld"],
    lengths: &[2, 2],
    payloads: include_bytes!("minecraft.world_clock.nbt"),
};

/// `minecraft:timeline` (4 elements, 4024 bytes of NBT).
pub static TIMELINE: RegistryContents = RegistryContents {
    registry: "minecraft:timeline",
    ids: &[
        "minecraft:moon",
        "minecraft:day",
        "minecraft:early_game",
        "minecraft:villager_schedule",
    ],
    lengths: &[393, 3550, 31, 50],
    payloads: include_bytes!("minecraft.timeline.nbt"),
};
