services:
  hyperion-proxy:
    image: ghcr.io/hyperion-mc/hyperion/antithesis-hyperion-proxy:latest
    platform: linux/amd64
    build:
      context: ..
      dockerfile: Dockerfile
      target: antithesis-hyperion-proxy
    ports:
      - "25565:25565"
    command: [ "--server", "tag:35565", "0.0.0.0:25565" ]
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    networks:
      - proxy-network
    depends_on:
      - tag
  tag:
    image: ghcr.io/hyperion-mc/hyperion/antithesis-tag:latest
    platform: linux/amd64
    ports:
      - "27750:27750"
    expose:
      - "35565"
    command: [ ]
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    networks:
      - proxy-network

    build:
      context: ..
      dockerfile: Dockerfile
      target: antithesis-tag

  antithesis-bot:
    image: ghcr.io/hyperion-mc/hyperion/antithesis-bot:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - HOST=hyperion-proxy:25565
      - RUST_LOG=info
    networks:
      - proxy-network


    build:
      context: ..
      dockerfile: Dockerfile
      target: antithesis-bot

networks:
  proxy-network:
    driver: bridge