use flecs_ecs::{core::ComponentOrPairId, macros::Component};
use hyperion_minecraft_proto::entity_type::EntityType;

/// What kind of thing an entity is.
///
/// The discriminants are flecs enum tags and carry no protocol meaning. They
/// used to be sent as `minecraft:entity_type` ids, which worked only because
/// 1.20.1 happened to number that registry the way this list is ordered;
/// [`Self::entity_type`] is now the only thing allowed to produce an id.
#[derive(Component, Copy, Clone, Debug, PartialEq, Eq, Hash)]
#[repr(C)]
#[flecs(meta)]
pub enum EntityKind {
    Allay,
    AreaEffectCloud,
    ArmorStand,
    Arrow,
    Axolotl,
    Bat,
    Bee,
    Blaze,
    BlockDisplay,
    Boat,
    Camel,
    Cat,
    CaveSpider,
    ChestBoat,
    ChestMinecart,
    Chicken,
    Cod,
    CommandBlockMinecart,
    Cow,
    Creeper,
    Dolphin,
    Donkey,
    DragonFireball,
    Drowned,
    Egg,
    ElderGuardian,
    EndCrystal,
    EnderDragon,
    EnderPearl,
    Enderman,
    Endermite,
    Evoker,
    EvokerFangs,
    ExperienceBottle,
    ExperienceOrb,
    EyeOfEnder,
    FallingBlock,
    FireworkRocket,
    Fox,
    Frog,
    FurnaceMinecart,
    Ghast,
    Giant,
    GlowItemFrame,
    GlowSquid,
    Goat,
    Guardian,
    Hoglin,
    HopperMinecart,
    Horse,
    Husk,
    Illusioner,
    Interaction,
    IronGolem,
    Item,
    ItemDisplay,
    ItemFrame,
    Fireball,
    LeashKnot,
    Lightning,
    Llama,
    LlamaSpit,
    MagmaCube,
    Marker,
    Minecart,
    Mooshroom,
    Mule,
    Ocelot,
    Painting,
    Panda,
    Parrot,
    Phantom,
    Pig,
    Piglin,
    PiglinBrute,
    Pillager,
    PolarBear,
    Potion,
    Pufferfish,
    Rabbit,
    Ravager,
    Salmon,
    Sheep,
    Shulker,
    ShulkerBullet,
    Silverfish,
    Skeleton,
    SkeletonHorse,
    Slime,
    SmallFireball,
    Sniffer,
    SnowGolem,
    Snowball,
    SpawnerMinecart,
    SpectralArrow,
    Spider,
    Squid,
    Stray,
    Strider,
    Tadpole,
    TextDisplay,
    Tnt,
    TntMinecart,
    TraderLlama,
    Trident,
    TropicalFish,
    Turtle,
    Vex,
    Villager,
    Vindicator,
    WanderingTrader,
    Warden,
    Witch,
    Wither,
    WitherSkeleton,
    WitherSkull,
    Wolf,
    Zoglin,
    Zombie,
    ZombieHorse,
    ZombieVillager,
    ZombifiedPiglin,
    Player,
    FishingBobber,
    Gui,
}

impl EntityKind {
    /// The Minecraft entity type this kind spawns as.
    ///
    /// `None` for the four kinds this protocol version has no type for, named
    /// in the last arm. A caller that has to send an id should say so with
    /// [`Self::expect_entity_type`] rather than substituting another type,
    /// which would put the wrong thing in the world instead of nothing.
    ///
    /// Every arm names a constant from the generated table, so a version bump
    /// that renames or drops a type stops this file compiling rather than
    /// leaving a stale id to be discovered on the wire.
    #[must_use]
    pub const fn entity_type(self) -> Option<EntityType> {
        let entity_type = match self {
            Self::Allay => EntityType::ALLAY,
            Self::AreaEffectCloud => EntityType::AREA_EFFECT_CLOUD,
            Self::ArmorStand => EntityType::ARMOR_STAND,
            Self::Arrow => EntityType::ARROW,
            Self::Axolotl => EntityType::AXOLOTL,
            Self::Bat => EntityType::BAT,
            Self::Bee => EntityType::BEE,
            Self::Blaze => EntityType::BLAZE,
            Self::BlockDisplay => EntityType::BLOCK_DISPLAY,
            Self::Camel => EntityType::CAMEL,
            Self::Cat => EntityType::CAT,
            Self::CaveSpider => EntityType::CAVE_SPIDER,
            Self::ChestMinecart => EntityType::CHEST_MINECART,
            Self::Chicken => EntityType::CHICKEN,
            Self::Cod => EntityType::COD,
            Self::CommandBlockMinecart => EntityType::COMMAND_BLOCK_MINECART,
            Self::Cow => EntityType::COW,
            Self::Creeper => EntityType::CREEPER,
            Self::Dolphin => EntityType::DOLPHIN,
            Self::Donkey => EntityType::DONKEY,
            Self::DragonFireball => EntityType::DRAGON_FIREBALL,
            Self::Drowned => EntityType::DROWNED,
            Self::Egg => EntityType::EGG,
            Self::ElderGuardian => EntityType::ELDER_GUARDIAN,
            Self::EndCrystal => EntityType::END_CRYSTAL,
            Self::EnderDragon => EntityType::ENDER_DRAGON,
            Self::EnderPearl => EntityType::ENDER_PEARL,
            Self::Enderman => EntityType::ENDERMAN,
            Self::Endermite => EntityType::ENDERMITE,
            Self::Evoker => EntityType::EVOKER,
            Self::EvokerFangs => EntityType::EVOKER_FANGS,
            Self::ExperienceBottle => EntityType::EXPERIENCE_BOTTLE,
            Self::ExperienceOrb => EntityType::EXPERIENCE_ORB,
            Self::EyeOfEnder => EntityType::EYE_OF_ENDER,
            Self::FallingBlock => EntityType::FALLING_BLOCK,
            Self::FireworkRocket => EntityType::FIREWORK_ROCKET,
            Self::Fox => EntityType::FOX,
            Self::Frog => EntityType::FROG,
            Self::FurnaceMinecart => EntityType::FURNACE_MINECART,
            Self::Ghast => EntityType::GHAST,
            Self::Giant => EntityType::GIANT,
            Self::GlowItemFrame => EntityType::GLOW_ITEM_FRAME,
            Self::GlowSquid => EntityType::GLOW_SQUID,
            Self::Goat => EntityType::GOAT,
            Self::Guardian => EntityType::GUARDIAN,
            Self::Hoglin => EntityType::HOGLIN,
            Self::HopperMinecart => EntityType::HOPPER_MINECART,
            Self::Horse => EntityType::HORSE,
            Self::Husk => EntityType::HUSK,
            Self::Illusioner => EntityType::ILLUSIONER,
            Self::Interaction => EntityType::INTERACTION,
            Self::IronGolem => EntityType::IRON_GOLEM,
            Self::Item => EntityType::ITEM,
            Self::ItemDisplay => EntityType::ITEM_DISPLAY,
            Self::ItemFrame => EntityType::ITEM_FRAME,
            Self::Fireball => EntityType::FIREBALL,
            Self::LeashKnot => EntityType::LEASH_KNOT,
            Self::Lightning => EntityType::LIGHTNING_BOLT,
            Self::Llama => EntityType::LLAMA,
            Self::LlamaSpit => EntityType::LLAMA_SPIT,
            Self::MagmaCube => EntityType::MAGMA_CUBE,
            Self::Marker => EntityType::MARKER,
            Self::Minecart => EntityType::MINECART,
            Self::Mooshroom => EntityType::MOOSHROOM,
            Self::Mule => EntityType::MULE,
            Self::Ocelot => EntityType::OCELOT,
            Self::Painting => EntityType::PAINTING,
            Self::Panda => EntityType::PANDA,
            Self::Parrot => EntityType::PARROT,
            Self::Phantom => EntityType::PHANTOM,
            Self::Pig => EntityType::PIG,
            Self::Piglin => EntityType::PIGLIN,
            Self::PiglinBrute => EntityType::PIGLIN_BRUTE,
            Self::Pillager => EntityType::PILLAGER,
            Self::PolarBear => EntityType::POLAR_BEAR,
            Self::Pufferfish => EntityType::PUFFERFISH,
            Self::Rabbit => EntityType::RABBIT,
            Self::Ravager => EntityType::RAVAGER,
            Self::Salmon => EntityType::SALMON,
            Self::Sheep => EntityType::SHEEP,
            Self::Shulker => EntityType::SHULKER,
            Self::ShulkerBullet => EntityType::SHULKER_BULLET,
            Self::Silverfish => EntityType::SILVERFISH,
            Self::Skeleton => EntityType::SKELETON,
            Self::SkeletonHorse => EntityType::SKELETON_HORSE,
            Self::Slime => EntityType::SLIME,
            Self::SmallFireball => EntityType::SMALL_FIREBALL,
            Self::Sniffer => EntityType::SNIFFER,
            Self::SnowGolem => EntityType::SNOW_GOLEM,
            Self::Snowball => EntityType::SNOWBALL,
            Self::SpawnerMinecart => EntityType::SPAWNER_MINECART,
            Self::SpectralArrow => EntityType::SPECTRAL_ARROW,
            Self::Spider => EntityType::SPIDER,
            Self::Squid => EntityType::SQUID,
            Self::Stray => EntityType::STRAY,
            Self::Strider => EntityType::STRIDER,
            Self::Tadpole => EntityType::TADPOLE,
            Self::TextDisplay => EntityType::TEXT_DISPLAY,
            Self::Tnt => EntityType::TNT,
            Self::TntMinecart => EntityType::TNT_MINECART,
            Self::TraderLlama => EntityType::TRADER_LLAMA,
            Self::Trident => EntityType::TRIDENT,
            Self::TropicalFish => EntityType::TROPICAL_FISH,
            Self::Turtle => EntityType::TURTLE,
            Self::Vex => EntityType::VEX,
            Self::Villager => EntityType::VILLAGER,
            Self::Vindicator => EntityType::VINDICATOR,
            Self::WanderingTrader => EntityType::WANDERING_TRADER,
            Self::Warden => EntityType::WARDEN,
            Self::Witch => EntityType::WITCH,
            Self::Wither => EntityType::WITHER,
            Self::WitherSkeleton => EntityType::WITHER_SKELETON,
            Self::WitherSkull => EntityType::WITHER_SKULL,
            Self::Wolf => EntityType::WOLF,
            Self::Zoglin => EntityType::ZOGLIN,
            Self::Zombie => EntityType::ZOMBIE,
            Self::ZombieHorse => EntityType::ZOMBIE_HORSE,
            Self::ZombieVillager => EntityType::ZOMBIE_VILLAGER,
            Self::ZombifiedPiglin => EntityType::ZOMBIFIED_PIGLIN,
            Self::Player => EntityType::PLAYER,
            Self::FishingBobber => EntityType::FISHING_BOBBER,
            // Nothing in 26.2 to point at: `minecraft:boat` and
            // `minecraft:chest_boat` became one type per wood in 1.21.2,
            // `minecraft:potion` split into splash and lingering, and `Gui` is
            // this server's holder for an open inventory rather than anything a
            // client is ever told about.
            Self::Boat | Self::ChestBoat | Self::Potion | Self::Gui => return None,
        };
        Some(entity_type)
    }

    /// [`Self::entity_type`], for a caller with no way to carry on without one.
    ///
    /// # Panics
    /// Panics naming the kind. Reaching this means something enqueued a spawn
    /// for a kind no client can be told about, which is a bug in the caller
    /// rather than a condition to recover from.
    #[must_use]
    pub fn expect_entity_type(self) -> EntityType {
        self.entity_type().unwrap_or_else(|| {
            panic!("{self:?} has no minecraft:entity_type in this version, so it cannot be spawned")
        })
    }
}
