#![expect(
    nonstandard_style,
    reason = "Most of this code is generated by macros. It is easier, simpler, and faster in \
              terms of compilation speed to use the packet and state names as-is from \
              for_each_pre_play_state than it is to use the paste macro to convert them to the \
              appropriate casing"
)]

use flecs_ecs::prelude::*;
use paste::paste;
use tracing::error;
use valence_protocol::Packet as _;

use crate::{
    net::{Compose, ConnectionId, PacketDecoder, decoder::BorrowedPacketFrame},
    simulation::{
        ConfirmBlockSequences, EntitySize, PacketState, Pitch, Position, Yaw,
        animation::ActiveAnimation,
        blocks::Blocks,
        handlers::{PacketSwitchQuery, packet_switch},
        metadata::entity::Pose,
        packet::{HandlerRegistry, Packet},
    },
    storage::Events,
};

mod __private {
    use std::cell::RefCell;

    use flecs_ecs::macros::Component;
    use thread_local::ThreadLocal;

    #[derive(Default, Component)]
    pub struct Decompressor(pub ThreadLocal<RefCell<libdeflater::Decompressor>>);
}

/// The decoded packets of each pre-play protocol state, waiting to be processed.
///
/// There is one singleton per protocol state. Decoding systems append to them concurrently
/// ([`boxcar::Vec::push`] only needs `&self`) during [`flecs::pipeline::PreUpdate`], and the
/// systems which act on the packets take the contents with [`std::mem::take`] during
/// [`flecs::pipeline::OnUpdate`].
///
/// Play packets are not queued; they are dispatched straight to
/// [`crate::simulation::packet::HandlerRegistry`] by `recv_data`.
///
/// hyperion's own [`crate::storage::Events`] queue is not usable here because its
/// `define_events!` registration cannot express the `packet::<state>::<packet>` paths generated
/// below.
pub mod queues {
    use flecs_ecs::macros::Component;

    use crate::simulation::packet;

    hyperion_packet_macros::for_each_pre_play_state! {
        #{
            #for_each_packet! {
                #[derive(Default, Component)]
                pub struct #state {
                    #{pub #packet_name: boxcar::Vec<packet::#state::#packet_name>,}
                }
            }
        }
    }
}

/// Whether the protocol may transition to another state after a packet in one of these states are
/// sent
mod may_transition {
    pub const handshake: bool = true;
    pub const status: bool = false;
    pub const login: bool = true;
}

fn try_next_frame(
    compose: &Compose,
    connection_id: ConnectionId,
    decoder: &PacketDecoder,
    decompressor: &mut libdeflater::Decompressor,
    receiver: &mut packet_channel::Receiver,
) -> Option<BorrowedPacketFrame> {
    let raw_packet = receiver.try_recv()?;
    match decoder.try_next_packet(decompressor, raw_packet) {
        Ok(packet) => Some(packet),
        Err(e) => {
            error!("failed to decode packet: {e}");
            compose.io_buf().shutdown(connection_id);
            None
        }
    }
}

hyperion_packet_macros::for_each_pre_play_state! {
    #{
        paste! {
            fn [<register_ #state>](world: &World) {
                world
                    .component::<queues::#state>()
                    .add_trait::<flecs::Singleton>();
                world.set(queues::#state::default());

                world
                    .system_named::<(
                        &Compose,
                        &__private::Decompressor,
                        &queues::#state,
                        &ConnectionId,
                        &PacketDecoder,
                        &mut packet_channel::Receiver,
                    )>(stringify!([<decode_ #state>]))
                    .with_enum(PacketState::[<#state:camel>])
                    .kind(id::<flecs::pipeline::PreUpdate>())
                    .par_each_entity(|entity, (
                        compose,
                        decompressor,
                        queue,
                        connection_id,
                        decoder,
                        receiver,
                    )| {
                        let sender = entity.id();
                        let connection_id = *connection_id;
                        let mut decompressor = decompressor.0.get_or_default().borrow_mut();

                        loop {
                            let Some(frame) = try_next_frame(
                                compose,
                                connection_id,
                                decoder,
                                &mut decompressor,
                                receiver,
                            ) else {
                                break;
                            };

                            let frame_id = frame.id;

                            #for_each_packet! {
                                let result: anyhow::Result<()> = match frame_id {
                                    #{
                                        #valence_packet::ID => {
                                            match frame.decode::<#static_valence_packet>() {
                                                Ok(data) => {
                                                    queue.#packet_name.push(Packet::new(
                                                        sender,
                                                        connection_id,
                                                        data
                                                    ));
                                                    Ok(())
                                                },
                                                Err(e) => Err(e)
                                            }
                                        },
                                    }
                                    _ => {
                                        Err(anyhow::Error::msg("invalid packet id"))
                                    }
                                };
                            }

                            if let Err(e) = result {
                                // The call to error! is placed outside of the match statement to help reduce
                                // compile times by reducing code duplication from the expansion of the error!
                                // macro
                                error!("error while decoding packet (id: {frame_id}): {e}");
                                compose.io_buf().shutdown(connection_id);
                                break;
                            }

                            if may_transition::#state {
                                // The packet handler for this packet might change the player to
                                // another packet state, so more packets cannot be decoded at this
                                // moment
                                break;
                            }
                        }
                    });
            }
        }
    }
}

/// Decodes and dispatches play packets.
///
/// Unlike the pre-play states this runs single-threaded, because handlers spawn entities and flecs
/// forbids that inside a multithreaded system.
fn register_play(world: &World) {
    system!(
        "recv_data",
        world,
        &Compose,
        &Blocks,
        &HandlerRegistry,
        &Events,
        &hyperion_crafting::CraftingRegistry,
        &__private::Decompressor,
        &ConnectionId,
        &PacketDecoder,
        &mut packet_channel::Receiver,
        ?&mut Position,
        &mut Yaw,
        &mut Pitch,
        &mut EntitySize,
        ?&mut Pose,
        &mut ConfirmBlockSequences,
        &mut hyperion_inventory::PlayerInventory,
        &mut ActiveAnimation,
    )
    .with_enum(PacketState::Play)
    .kind(id::<flecs::pipeline::OnUpdate>())
    .each_iter(
        |it,
         row,
         (
            compose,
            blocks,
            handler_registry,
            events,
            crafting_registry,
            decompressor,
            connection_id,
            decoder,
            receiver,
            position,
            yaw,
            pitch,
            size,
            pose,
            confirm_block_sequences,
            inventory,
            animation,
        )| {
            let world = it.world();
            let view = it.entity(row);
            let id = view.id();
            let connection_id = *connection_id;
            let mut decompressor = decompressor.0.get_or_default().borrow_mut();

            // Transitioning to play is just a way to make sure that the player is officially in
            // play before we start sending them play packets, so a player without a position or
            // pose is not ready to be simulated yet.
            let Some((position, pose)) = position.zip(pose) else {
                return;
            };

            let mut query = PacketSwitchQuery {
                id,
                handler_registry,
                view,
                compose,
                io_ref: connection_id,
                position,
                yaw,
                pitch,
                size,
                world: &world,
                blocks,
                pose,
                events,
                confirm_block_sequences,
                inventory,
                animation,
                crafting_registry,
            };

            while let Some(frame) =
                try_next_frame(compose, connection_id, decoder, &mut decompressor, receiver)
            {
                let frame_id = frame.id;
                if let Err(e) = packet_switch(frame, &mut query) {
                    error!("error while processing packet (id: {frame_id}): {e}");
                }
            }
        },
    );
}

#[derive(Component)]
pub struct DecodeModule;

impl Module for DecodeModule {
    fn module(world: &World) {
        world.component::<packet_channel::Receiver>();

        world
            .component::<__private::Decompressor>()
            .add_trait::<flecs::Singleton>();
        world.set(__private::Decompressor::default());

        hyperion_packet_macros::for_each_pre_play_state! {
            #{
                paste! {
                    [<register_ #state>](world);
                }
            }
        }

        register_play(world);
    }
}
